// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/exoscale/cluster-api-provider-exoscale/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewCloud creates a new instance of Cloud. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloud(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cloud {
	mock := &Cloud{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cloud is an autogenerated mock type for the Cloud type
type Cloud struct {
	mock.Mock
}

type Cloud_Expecter struct {
	mock *mock.Mock
}

func (_m *Cloud) EXPECT() *Cloud_Expecter {
	return &Cloud_Expecter{mock: &_m.Mock}
}

// CreateElasticIP provides a mock function for the type Cloud
func (_mock *Cloud) CreateElasticIP(ctx context.Context, healthCheckPort int32, description string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, healthCheckPort, description)

	if len(ret) == 0 {
		panic("no return value specified for CreateElasticIP")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, healthCheckPort, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, healthCheckPort, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, string) error); ok {
		r1 = returnFunc(ctx, healthCheckPort, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cloud_CreateElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateElasticIP'
type Cloud_CreateElasticIP_Call struct {
	*mock.Call
}

// CreateElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - healthCheckPort int32
//   - description string
func (_e *Cloud_Expecter) CreateElasticIP(ctx any, healthCheckPort any, description any) *Cloud_CreateElasticIP_Call {
	return &Cloud_CreateElasticIP_Call{Call: _e.mock.On("CreateElasticIP", ctx, healthCheckPort, description)}
}

func (_c *Cloud_CreateElasticIP_Call) Run(run func(ctx context.Context, healthCheckPort int32, description string)) *Cloud_CreateElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cloud_CreateElasticIP_Call) Return(uUID uuid.UUID, err error) *Cloud_CreateElasticIP_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *Cloud_CreateElasticIP_Call) RunAndReturn(run func(ctx context.Context, healthCheckPort int32, description string) (uuid.UUID, error)) *Cloud_CreateElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecurityGroup provides a mock function for the type Cloud
func (_mock *Cloud) CreateSecurityGroup(ctx context.Context, name string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecurityGroup")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cloud_CreateSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecurityGroup'
type Cloud_CreateSecurityGroup_Call struct {
	*mock.Call
}

// CreateSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Cloud_Expecter) CreateSecurityGroup(ctx any, name any) *Cloud_CreateSecurityGroup_Call {
	return &Cloud_CreateSecurityGroup_Call{Call: _e.mock.On("CreateSecurityGroup", ctx, name)}
}

func (_c *Cloud_CreateSecurityGroup_Call) Run(run func(ctx context.Context, name string)) *Cloud_CreateSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cloud_CreateSecurityGroup_Call) Return(uUID uuid.UUID, err error) *Cloud_CreateSecurityGroup_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *Cloud_CreateSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, name string) (uuid.UUID, error)) *Cloud_CreateSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecurityGroupRule provides a mock function for the type Cloud
func (_mock *Cloud) CreateSecurityGroupRule(ctx context.Context, sgID uuid.UUID, rule domain.SecurityGroupRule) (uuid.UUID, error) {
	ret := _mock.Called(ctx, sgID, rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecurityGroupRule")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.SecurityGroupRule) (uuid.UUID, error)); ok {
		return returnFunc(ctx, sgID, rule)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.SecurityGroupRule) uuid.UUID); ok {
		r0 = returnFunc(ctx, sgID, rule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.SecurityGroupRule) error); ok {
		r1 = returnFunc(ctx, sgID, rule)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cloud_CreateSecurityGroupRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecurityGroupRule'
type Cloud_CreateSecurityGroupRule_Call struct {
	*mock.Call
}

// CreateSecurityGroupRule is a helper method to define mock.On call
//   - ctx context.Context
//   - sgID uuid.UUID
//   - rule domain.SecurityGroupRule
func (_e *Cloud_Expecter) CreateSecurityGroupRule(ctx any, sgID any, rule any) *Cloud_CreateSecurityGroupRule_Call {
	return &Cloud_CreateSecurityGroupRule_Call{Call: _e.mock.On("CreateSecurityGroupRule", ctx, sgID, rule)}
}

func (_c *Cloud_CreateSecurityGroupRule_Call) Run(run func(ctx context.Context, sgID uuid.UUID, rule domain.SecurityGroupRule)) *Cloud_CreateSecurityGroupRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.SecurityGroupRule
		if args[2] != nil {
			arg2 = args[2].(domain.SecurityGroupRule)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cloud_CreateSecurityGroupRule_Call) Return(uUID uuid.UUID, err error) *Cloud_CreateSecurityGroupRule_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *Cloud_CreateSecurityGroupRule_Call) RunAndReturn(run func(ctx context.Context, sgID uuid.UUID, rule domain.SecurityGroupRule) (uuid.UUID, error)) *Cloud_CreateSecurityGroupRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteElasticIP provides a mock function for the type Cloud
func (_mock *Cloud) DeleteElasticIP(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteElasticIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cloud_DeleteElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteElasticIP'
type Cloud_DeleteElasticIP_Call struct {
	*mock.Call
}

// DeleteElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Cloud_Expecter) DeleteElasticIP(ctx any, id any) *Cloud_DeleteElasticIP_Call {
	return &Cloud_DeleteElasticIP_Call{Call: _e.mock.On("DeleteElasticIP", ctx, id)}
}

func (_c *Cloud_DeleteElasticIP_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Cloud_DeleteElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cloud_DeleteElasticIP_Call) Return(err error) *Cloud_DeleteElasticIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cloud_DeleteElasticIP_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *Cloud_DeleteElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecurityGroup provides a mock function for the type Cloud
func (_mock *Cloud) DeleteSecurityGroup(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecurityGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cloud_DeleteSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecurityGroup'
type Cloud_DeleteSecurityGroup_Call struct {
	*mock.Call
}

// DeleteSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Cloud_Expecter) DeleteSecurityGroup(ctx any, id any) *Cloud_DeleteSecurityGroup_Call {
	return &Cloud_DeleteSecurityGroup_Call{Call: _e.mock.On("DeleteSecurityGroup", ctx, id)}
}

func (_c *Cloud_DeleteSecurityGroup_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Cloud_DeleteSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cloud_DeleteSecurityGroup_Call) Return(err error) *Cloud_DeleteSecurityGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cloud_DeleteSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *Cloud_DeleteSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecurityGroupRule provides a mock function for the type Cloud
func (_mock *Cloud) DeleteSecurityGroupRule(ctx context.Context, sgID uuid.UUID, ruleID uuid.UUID) error {
	ret := _mock.Called(ctx, sgID, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecurityGroupRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sgID, ruleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cloud_DeleteSecurityGroupRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecurityGroupRule'
type Cloud_DeleteSecurityGroupRule_Call struct {
	*mock.Call
}

// DeleteSecurityGroupRule is a helper method to define mock.On call
//   - ctx context.Context
//   - sgID uuid.UUID
//   - ruleID uuid.UUID
func (_e *Cloud_Expecter) DeleteSecurityGroupRule(ctx any, sgID any, ruleID any) *Cloud_DeleteSecurityGroupRule_Call {
	return &Cloud_DeleteSecurityGroupRule_Call{Call: _e.mock.On("DeleteSecurityGroupRule", ctx, sgID, ruleID)}
}

func (_c *Cloud_DeleteSecurityGroupRule_Call) Run(run func(ctx context.Context, sgID uuid.UUID, ruleID uuid.UUID)) *Cloud_DeleteSecurityGroupRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cloud_DeleteSecurityGroupRule_Call) Return(err error) *Cloud_DeleteSecurityGroupRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cloud_DeleteSecurityGroupRule_Call) RunAndReturn(run func(ctx context.Context, sgID uuid.UUID, ruleID uuid.UUID) error) *Cloud_DeleteSecurityGroupRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetElasticIP provides a mock function for the type Cloud
func (_mock *Cloud) GetElasticIP(ctx context.Context, id uuid.UUID) (domain.ElasticIP, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetElasticIP")
	}

	var r0 domain.ElasticIP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.ElasticIP, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.ElasticIP); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.ElasticIP)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cloud_GetElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetElasticIP'
type Cloud_GetElasticIP_Call struct {
	*mock.Call
}

// GetElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Cloud_Expecter) GetElasticIP(ctx any, id any) *Cloud_GetElasticIP_Call {
	return &Cloud_GetElasticIP_Call{Call: _e.mock.On("GetElasticIP", ctx, id)}
}

func (_c *Cloud_GetElasticIP_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Cloud_GetElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cloud_GetElasticIP_Call) Return(elasticIP domain.ElasticIP, err error) *Cloud_GetElasticIP_Call {
	_c.Call.Return(elasticIP, err)
	return _c
}

func (_c *Cloud_GetElasticIP_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.ElasticIP, error)) *Cloud_GetElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecurityGroup provides a mock function for the type Cloud
func (_mock *Cloud) GetSecurityGroup(ctx context.Context, id uuid.UUID) (domain.SecurityGroup, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSecurityGroup")
	}

	var r0 domain.SecurityGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.SecurityGroup, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.SecurityGroup); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.SecurityGroup)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cloud_GetSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecurityGroup'
type Cloud_GetSecurityGroup_Call struct {
	*mock.Call
}

// GetSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Cloud_Expecter) GetSecurityGroup(ctx any, id any) *Cloud_GetSecurityGroup_Call {
	return &Cloud_GetSecurityGroup_Call{Call: _e.mock.On("GetSecurityGroup", ctx, id)}
}

func (_c *Cloud_GetSecurityGroup_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Cloud_GetSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cloud_GetSecurityGroup_Call) Return(securityGroup domain.SecurityGroup, err error) *Cloud_GetSecurityGroup_Call {
	_c.Call.Return(securityGroup, err)
	return _c
}

func (_c *Cloud_GetSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.SecurityGroup, error)) *Cloud_GetSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ListElasticIPs provides a mock function for the type Cloud
func (_mock *Cloud) ListElasticIPs(ctx context.Context) ([]domain.ElasticIP, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListElasticIPs")
	}

	var r0 []domain.ElasticIP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.ElasticIP, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.ElasticIP); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ElasticIP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cloud_ListElasticIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListElasticIPs'
type Cloud_ListElasticIPs_Call struct {
	*mock.Call
}

// ListElasticIPs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Cloud_Expecter) ListElasticIPs(ctx any) *Cloud_ListElasticIPs_Call {
	return &Cloud_ListElasticIPs_Call{Call: _e.mock.On("ListElasticIPs", ctx)}
}

func (_c *Cloud_ListElasticIPs_Call) Run(run func(ctx context.Context)) *Cloud_ListElasticIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Cloud_ListElasticIPs_Call) Return(elasticIPs []domain.ElasticIP, err error) *Cloud_ListElasticIPs_Call {
	_c.Call.Return(elasticIPs, err)
	return _c
}

func (_c *Cloud_ListElasticIPs_Call) RunAndReturn(run func(ctx context.Context) ([]domain.ElasticIP, error)) *Cloud_ListElasticIPs_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecurityGroupRules provides a mock function for the type Cloud
func (_mock *Cloud) ListSecurityGroupRules(ctx context.Context, sgID uuid.UUID) ([]domain.SecurityGroupRule, error) {
	ret := _mock.Called(ctx, sgID)

	if len(ret) == 0 {
		panic("no return value specified for ListSecurityGroupRules")
	}

	var r0 []domain.SecurityGroupRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.SecurityGroupRule, error)); ok {
		return returnFunc(ctx, sgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.SecurityGroupRule); ok {
		r0 = returnFunc(ctx, sgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SecurityGroupRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cloud_ListSecurityGroupRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecurityGroupRules'
type Cloud_ListSecurityGroupRules_Call struct {
	*mock.Call
}

// ListSecurityGroupRules is a helper method to define mock.On call
//   - ctx context.Context
//   - sgID uuid.UUID
func (_e *Cloud_Expecter) ListSecurityGroupRules(ctx any, sgID any) *Cloud_ListSecurityGroupRules_Call {
	return &Cloud_ListSecurityGroupRules_Call{Call: _e.mock.On("ListSecurityGroupRules", ctx, sgID)}
}

func (_c *Cloud_ListSecurityGroupRules_Call) Run(run func(ctx context.Context, sgID uuid.UUID)) *Cloud_ListSecurityGroupRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cloud_ListSecurityGroupRules_Call) Return(securityGroupRules []domain.SecurityGroupRule, err error) *Cloud_ListSecurityGroupRules_Call {
	_c.Call.Return(securityGroupRules, err)
	return _c
}

func (_c *Cloud_ListSecurityGroupRules_Call) RunAndReturn(run func(ctx context.Context, sgID uuid.UUID) ([]domain.SecurityGroupRule, error)) *Cloud_ListSecurityGroupRules_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateElasticIP provides a mock function for the type Cloud
func (_mock *Cloud) UpdateElasticIP(ctx context.Context, eip domain.ElasticIP) error {
	ret := _mock.Called(ctx, eip)

	if len(ret) == 0 {
		panic("no return value specified for UpdateElasticIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ElasticIP) error); ok {
		r0 = returnFunc(ctx, eip)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cloud_UpdateElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateElasticIP'
type Cloud_UpdateElasticIP_Call struct {
	*mock.Call
}

// UpdateElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - eip domain.ElasticIP
func (_e *Cloud_Expecter) UpdateElasticIP(ctx any, eip any) *Cloud_UpdateElasticIP_Call {
	return &Cloud_UpdateElasticIP_Call{Call: _e.mock.On("UpdateElasticIP", ctx, eip)}
}

func (_c *Cloud_UpdateElasticIP_Call) Run(run func(ctx context.Context, eip domain.ElasticIP)) *Cloud_UpdateElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ElasticIP
		if args[1] != nil {
			arg1 = args[1].(domain.ElasticIP)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cloud_UpdateElasticIP_Call) Return(err error) *Cloud_UpdateElasticIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cloud_UpdateElasticIP_Call) RunAndReturn(run func(ctx context.Context, eip domain.ElasticIP) error) *Cloud_UpdateElasticIP_Call {
	_c.Call.Return(run)
	return _c
}
