// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/exoscale/cluster-api-provider-exoscale/api/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// NewClusterService creates a new instance of ClusterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ClusterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ClusterService is an autogenerated mock type for the ClusterService type
type ClusterService struct {
	mock.Mock
}

type ClusterService_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterService) EXPECT() *ClusterService_Expecter {
	return &ClusterService_Expecter{mock: &_m.Mock}
}

// DeleteCluster provides a mock function for the type ClusterService
func (_mock *ClusterService) DeleteCluster(ctx context.Context, cluster v1alpha1.ExoscaleCluster) (v1alpha1.ExoscaleCluster, error) {
	ret := _mock.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCluster")
	}

	var r0 v1alpha1.ExoscaleCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1alpha1.ExoscaleCluster) (v1alpha1.ExoscaleCluster, error)); ok {
		return returnFunc(ctx, cluster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1alpha1.ExoscaleCluster) v1alpha1.ExoscaleCluster); ok {
		r0 = returnFunc(ctx, cluster)
	} else {
		r0 = ret.Get(0).(v1alpha1.ExoscaleCluster)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v1alpha1.ExoscaleCluster) error); ok {
		r1 = returnFunc(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterService_DeleteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCluster'
type ClusterService_DeleteCluster_Call struct {
	*mock.Call
}

// DeleteCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster v1alpha1.ExoscaleCluster
func (_e *ClusterService_Expecter) DeleteCluster(ctx any, cluster any) *ClusterService_DeleteCluster_Call {
	return &ClusterService_DeleteCluster_Call{Call: _e.mock.On("DeleteCluster", ctx, cluster)}
}

func (_c *ClusterService_DeleteCluster_Call) Run(run func(ctx context.Context, cluster v1alpha1.ExoscaleCluster)) *ClusterService_DeleteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1alpha1.ExoscaleCluster
		if args[1] != nil {
			arg1 = args[1].(v1alpha1.ExoscaleCluster)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterService_DeleteCluster_Call) Return(exoscaleCluster v1alpha1.ExoscaleCluster, err error) *ClusterService_DeleteCluster_Call {
	_c.Call.Return(exoscaleCluster, err)
	return _c
}

func (_c *ClusterService_DeleteCluster_Call) RunAndReturn(run func(ctx context.Context, cluster v1alpha1.ExoscaleCluster) (v1alpha1.ExoscaleCluster, error)) *ClusterService_DeleteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileCluster provides a mock function for the type ClusterService
func (_mock *ClusterService) ReconcileCluster(ctx context.Context, cluster v1alpha1.ExoscaleCluster) (v1alpha1.ExoscaleCluster, error) {
	ret := _mock.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileCluster")
	}

	var r0 v1alpha1.ExoscaleCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1alpha1.ExoscaleCluster) (v1alpha1.ExoscaleCluster, error)); ok {
		return returnFunc(ctx, cluster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1alpha1.ExoscaleCluster) v1alpha1.ExoscaleCluster); ok {
		r0 = returnFunc(ctx, cluster)
	} else {
		r0 = ret.Get(0).(v1alpha1.ExoscaleCluster)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v1alpha1.ExoscaleCluster) error); ok {
		r1 = returnFunc(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterService_ReconcileCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileCluster'
type ClusterService_ReconcileCluster_Call struct {
	*mock.Call
}

// ReconcileCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster v1alpha1.ExoscaleCluster
func (_e *ClusterService_Expecter) ReconcileCluster(ctx any, cluster any) *ClusterService_ReconcileCluster_Call {
	return &ClusterService_ReconcileCluster_Call{Call: _e.mock.On("ReconcileCluster", ctx, cluster)}
}

func (_c *ClusterService_ReconcileCluster_Call) Run(run func(ctx context.Context, cluster v1alpha1.ExoscaleCluster)) *ClusterService_ReconcileCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1alpha1.ExoscaleCluster
		if args[1] != nil {
			arg1 = args[1].(v1alpha1.ExoscaleCluster)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterService_ReconcileCluster_Call) Return(exoscaleCluster v1alpha1.ExoscaleCluster, err error) *ClusterService_ReconcileCluster_Call {
	_c.Call.Return(exoscaleCluster, err)
	return _c
}

func (_c *ClusterService_ReconcileCluster_Call) RunAndReturn(run func(ctx context.Context, cluster v1alpha1.ExoscaleCluster) (v1alpha1.ExoscaleCluster, error)) *ClusterService_ReconcileCluster_Call {
	_c.Call.Return(run)
	return _c
}
