// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/exoscale/cluster-api-provider-exoscale/api/v1alpha1"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/util/validation/field"
)

// NewClusterValidator creates a new instance of ClusterValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterValidator {
	mock := &ClusterValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClusterValidator is an autogenerated mock type for the ClusterValidator type
type ClusterValidator struct {
	mock.Mock
}

type ClusterValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterValidator) EXPECT() *ClusterValidator_Expecter {
	return &ClusterValidator_Expecter{mock: &_m.Mock}
}

// ValidateCreate provides a mock function for the type ClusterValidator
func (_mock *ClusterValidator) ValidateCreate(spec v1alpha1.ExoscaleClusterSpec, fldPath *field.Path) field.ErrorList {
	ret := _mock.Called(spec, fldPath)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCreate")
	}

	var r0 field.ErrorList
	if returnFunc, ok := ret.Get(0).(func(v1alpha1.ExoscaleClusterSpec, *field.Path) field.ErrorList); ok {
		r0 = returnFunc(spec, fldPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(field.ErrorList)
		}
	}
	return r0
}

// ClusterValidator_ValidateCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCreate'
type ClusterValidator_ValidateCreate_Call struct {
	*mock.Call
}

// ValidateCreate is a helper method to define mock.On call
//   - spec v1alpha1.ExoscaleClusterSpec
//   - fldPath *field.Path
func (_e *ClusterValidator_Expecter) ValidateCreate(spec any, fldPath any) *ClusterValidator_ValidateCreate_Call {
	return &ClusterValidator_ValidateCreate_Call{Call: _e.mock.On("ValidateCreate", spec, fldPath)}
}

func (_c *ClusterValidator_ValidateCreate_Call) Run(run func(spec v1alpha1.ExoscaleClusterSpec, fldPath *field.Path)) *ClusterValidator_ValidateCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.ExoscaleClusterSpec
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.ExoscaleClusterSpec)
		}
		var arg1 *field.Path
		if args[1] != nil {
			arg1 = args[1].(*field.Path)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterValidator_ValidateCreate_Call) Return(errorList field.ErrorList) *ClusterValidator_ValidateCreate_Call {
	_c.Call.Return(errorList)
	return _c
}

func (_c *ClusterValidator_ValidateCreate_Call) RunAndReturn(run func(spec v1alpha1.ExoscaleClusterSpec, fldPath *field.Path) field.ErrorList) *ClusterValidator_ValidateCreate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUpdate provides a mock function for the type ClusterValidator
func (_mock *ClusterValidator) ValidateUpdate(oldSpec v1alpha1.ExoscaleClusterSpec, newSpec v1alpha1.ExoscaleClusterSpec, fldPath *field.Path) field.ErrorList {
	ret := _mock.Called(oldSpec, newSpec, fldPath)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUpdate")
	}

	var r0 field.ErrorList
	if returnFunc, ok := ret.Get(0).(func(v1alpha1.ExoscaleClusterSpec, v1alpha1.ExoscaleClusterSpec, *field.Path) field.ErrorList); ok {
		r0 = returnFunc(oldSpec, newSpec, fldPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(field.ErrorList)
		}
	}
	return r0
}

// ClusterValidator_ValidateUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUpdate'
type ClusterValidator_ValidateUpdate_Call struct {
	*mock.Call
}

// ValidateUpdate is a helper method to define mock.On call
//   - oldSpec v1alpha1.ExoscaleClusterSpec
//   - newSpec v1alpha1.ExoscaleClusterSpec
//   - fldPath *field.Path
func (_e *ClusterValidator_Expecter) ValidateUpdate(oldSpec any, newSpec any, fldPath any) *ClusterValidator_ValidateUpdate_Call {
	return &ClusterValidator_ValidateUpdate_Call{Call: _e.mock.On("ValidateUpdate", oldSpec, newSpec, fldPath)}
}

func (_c *ClusterValidator_ValidateUpdate_Call) Run(run func(oldSpec v1alpha1.ExoscaleClusterSpec, newSpec v1alpha1.ExoscaleClusterSpec, fldPath *field.Path)) *ClusterValidator_ValidateUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1alpha1.ExoscaleClusterSpec
		if args[0] != nil {
			arg0 = args[0].(v1alpha1.ExoscaleClusterSpec)
		}
		var arg1 v1alpha1.ExoscaleClusterSpec
		if args[1] != nil {
			arg1 = args[1].(v1alpha1.ExoscaleClusterSpec)
		}
		var arg2 *field.Path
		if args[2] != nil {
			arg2 = args[2].(*field.Path)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClusterValidator_ValidateUpdate_Call) Return(errorList field.ErrorList) *ClusterValidator_ValidateUpdate_Call {
	_c.Call.Return(errorList)
	return _c
}

func (_c *ClusterValidator_ValidateUpdate_Call) RunAndReturn(run func(oldSpec v1alpha1.ExoscaleClusterSpec, newSpec v1alpha1.ExoscaleClusterSpec, fldPath *field.Path) field.ErrorList) *ClusterValidator_ValidateUpdate_Call {
	_c.Call.Return(run)
	return _c
}
