// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/exoscale/cluster-api-provider-exoscale/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewElasticIPService creates a new instance of ElasticIPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElasticIPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElasticIPService {
	mock := &ElasticIPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ElasticIPService is an autogenerated mock type for the ElasticIPService type
type ElasticIPService struct {
	mock.Mock
}

type ElasticIPService_Expecter struct {
	mock *mock.Mock
}

func (_m *ElasticIPService) EXPECT() *ElasticIPService_Expecter {
	return &ElasticIPService_Expecter{mock: &_m.Mock}
}

// DeleteElasticIP provides a mock function for the type ElasticIPService
func (_mock *ElasticIPService) DeleteElasticIP(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteElasticIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ElasticIPService_DeleteElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteElasticIP'
type ElasticIPService_DeleteElasticIP_Call struct {
	*mock.Call
}

// DeleteElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ElasticIPService_Expecter) DeleteElasticIP(ctx any, id any) *ElasticIPService_DeleteElasticIP_Call {
	return &ElasticIPService_DeleteElasticIP_Call{Call: _e.mock.On("DeleteElasticIP", ctx, id)}
}

func (_c *ElasticIPService_DeleteElasticIP_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ElasticIPService_DeleteElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ElasticIPService_DeleteElasticIP_Call) Return(err error) *ElasticIPService_DeleteElasticIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ElasticIPService_DeleteElasticIP_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *ElasticIPService_DeleteElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// FindElasticIP provides a mock function for the type ElasticIPService
func (_mock *ElasticIPService) FindElasticIP(ctx context.Context, clusterID uuid.UUID, eipID *uuid.UUID) (domain.ElasticIP, error) {
	ret := _mock.Called(ctx, clusterID, eipID)

	if len(ret) == 0 {
		panic("no return value specified for FindElasticIP")
	}

	var r0 domain.ElasticIP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) (domain.ElasticIP, error)); ok {
		return returnFunc(ctx, clusterID, eipID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) domain.ElasticIP); ok {
		r0 = returnFunc(ctx, clusterID, eipID)
	} else {
		r0 = ret.Get(0).(domain.ElasticIP)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, clusterID, eipID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ElasticIPService_FindElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindElasticIP'
type ElasticIPService_FindElasticIP_Call struct {
	*mock.Call
}

// FindElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID uuid.UUID
//   - eipID *uuid.UUID
func (_e *ElasticIPService_Expecter) FindElasticIP(ctx any, clusterID any, eipID any) *ElasticIPService_FindElasticIP_Call {
	return &ElasticIPService_FindElasticIP_Call{Call: _e.mock.On("FindElasticIP", ctx, clusterID, eipID)}
}

func (_c *ElasticIPService_FindElasticIP_Call) Run(run func(ctx context.Context, clusterID uuid.UUID, eipID *uuid.UUID)) *ElasticIPService_FindElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ElasticIPService_FindElasticIP_Call) Return(elasticIP domain.ElasticIP, err error) *ElasticIPService_FindElasticIP_Call {
	_c.Call.Return(elasticIP, err)
	return _c
}

func (_c *ElasticIPService_FindElasticIP_Call) RunAndReturn(run func(ctx context.Context, clusterID uuid.UUID, eipID *uuid.UUID) (domain.ElasticIP, error)) *ElasticIPService_FindElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertElasticIP provides a mock function for the type ElasticIPService
func (_mock *ElasticIPService) UpsertElasticIP(ctx context.Context, clusterID uuid.UUID, eipID *uuid.UUID, port int32) (domain.ElasticIP, error) {
	ret := _mock.Called(ctx, clusterID, eipID, port)

	if len(ret) == 0 {
		panic("no return value specified for UpsertElasticIP")
	}

	var r0 domain.ElasticIP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, int32) (domain.ElasticIP, error)); ok {
		return returnFunc(ctx, clusterID, eipID, port)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, int32) domain.ElasticIP); ok {
		r0 = returnFunc(ctx, clusterID, eipID, port)
	} else {
		r0 = ret.Get(0).(domain.ElasticIP)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID, int32) error); ok {
		r1 = returnFunc(ctx, clusterID, eipID, port)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ElasticIPService_UpsertElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertElasticIP'
type ElasticIPService_UpsertElasticIP_Call struct {
	*mock.Call
}

// UpsertElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID uuid.UUID
//   - eipID *uuid.UUID
//   - port int32
func (_e *ElasticIPService_Expecter) UpsertElasticIP(ctx any, clusterID any, eipID any, port any) *ElasticIPService_UpsertElasticIP_Call {
	return &ElasticIPService_UpsertElasticIP_Call{Call: _e.mock.On("UpsertElasticIP", ctx, clusterID, eipID, port)}
}

func (_c *ElasticIPService_UpsertElasticIP_Call) Run(run func(ctx context.Context, clusterID uuid.UUID, eipID *uuid.UUID, port int32)) *ElasticIPService_UpsertElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ElasticIPService_UpsertElasticIP_Call) Return(elasticIP domain.ElasticIP, err error) *ElasticIPService_UpsertElasticIP_Call {
	_c.Call.Return(elasticIP, err)
	return _c
}

func (_c *ElasticIPService_UpsertElasticIP_Call) RunAndReturn(run func(ctx context.Context, clusterID uuid.UUID, eipID *uuid.UUID, port int32) (domain.ElasticIP, error)) *ElasticIPService_UpsertElasticIP_Call {
	_c.Call.Return(run)
	return _c
}
