// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/exoscale/egoscale/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewExoscaleClient creates a new instance of ExoscaleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExoscaleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExoscaleClient {
	mock := &ExoscaleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExoscaleClient is an autogenerated mock type for the ExoscaleClient type
type ExoscaleClient struct {
	mock.Mock
}

type ExoscaleClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ExoscaleClient) EXPECT() *ExoscaleClient_Expecter {
	return &ExoscaleClient_Expecter{mock: &_m.Mock}
}

// AddRuleToSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) AddRuleToSecurityGroup(ctx context.Context, id v3.UUID, req v3.AddRuleToSecurityGroupRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for AddRuleToSecurityGroup")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.AddRuleToSecurityGroupRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.AddRuleToSecurityGroupRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID, v3.AddRuleToSecurityGroupRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_AddRuleToSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRuleToSecurityGroup'
type ExoscaleClient_AddRuleToSecurityGroup_Call struct {
	*mock.Call
}

// AddRuleToSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
//   - req v3.AddRuleToSecurityGroupRequest
func (_e *ExoscaleClient_Expecter) AddRuleToSecurityGroup(ctx any, id any, req any) *ExoscaleClient_AddRuleToSecurityGroup_Call {
	return &ExoscaleClient_AddRuleToSecurityGroup_Call{Call: _e.mock.On("AddRuleToSecurityGroup", ctx, id, req)}
}

func (_c *ExoscaleClient_AddRuleToSecurityGroup_Call) Run(run func(ctx context.Context, id v3.UUID, req v3.AddRuleToSecurityGroupRequest)) *ExoscaleClient_AddRuleToSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		var arg2 v3.AddRuleToSecurityGroupRequest
		if args[2] != nil {
			arg2 = args[2].(v3.AddRuleToSecurityGroupRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExoscaleClient_AddRuleToSecurityGroup_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_AddRuleToSecurityGroup_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_AddRuleToSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID, req v3.AddRuleToSecurityGroupRequest) (*v3.Operation, error)) *ExoscaleClient_AddRuleToSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateElasticIP provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) CreateElasticIP(ctx context.Context, req v3.CreateElasticIPRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateElasticIP")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateElasticIPRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateElasticIPRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.CreateElasticIPRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_CreateElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateElasticIP'
type ExoscaleClient_CreateElasticIP_Call struct {
	*mock.Call
}

// CreateElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - req v3.CreateElasticIPRequest
func (_e *ExoscaleClient_Expecter) CreateElasticIP(ctx any, req any) *ExoscaleClient_CreateElasticIP_Call {
	return &ExoscaleClient_CreateElasticIP_Call{Call: _e.mock.On("CreateElasticIP", ctx, req)}
}

func (_c *ExoscaleClient_CreateElasticIP_Call) Run(run func(ctx context.Context, req v3.CreateElasticIPRequest)) *ExoscaleClient_CreateElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.CreateElasticIPRequest
		if args[1] != nil {
			arg1 = args[1].(v3.CreateElasticIPRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_CreateElasticIP_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_CreateElasticIP_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_CreateElasticIP_Call) RunAndReturn(run func(ctx context.Context, req v3.CreateElasticIPRequest) (*v3.Operation, error)) *ExoscaleClient_CreateElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) CreateSecurityGroup(ctx context.Context, req v3.CreateSecurityGroupRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecurityGroup")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateSecurityGroupRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateSecurityGroupRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.CreateSecurityGroupRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_CreateSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecurityGroup'
type ExoscaleClient_CreateSecurityGroup_Call struct {
	*mock.Call
}

// CreateSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - req v3.CreateSecurityGroupRequest
func (_e *ExoscaleClient_Expecter) CreateSecurityGroup(ctx any, req any) *ExoscaleClient_CreateSecurityGroup_Call {
	return &ExoscaleClient_CreateSecurityGroup_Call{Call: _e.mock.On("CreateSecurityGroup", ctx, req)}
}

func (_c *ExoscaleClient_CreateSecurityGroup_Call) Run(run func(ctx context.Context, req v3.CreateSecurityGroupRequest)) *ExoscaleClient_CreateSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.CreateSecurityGroupRequest
		if args[1] != nil {
			arg1 = args[1].(v3.CreateSecurityGroupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_CreateSecurityGroup_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_CreateSecurityGroup_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_CreateSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, req v3.CreateSecurityGroupRequest) (*v3.Operation, error)) *ExoscaleClient_CreateSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteElasticIP provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) DeleteElasticIP(ctx context.Context, id v3.UUID) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteElasticIP")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.Operation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_DeleteElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteElasticIP'
type ExoscaleClient_DeleteElasticIP_Call struct {
	*mock.Call
}

// DeleteElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) DeleteElasticIP(ctx any, id any) *ExoscaleClient_DeleteElasticIP_Call {
	return &ExoscaleClient_DeleteElasticIP_Call{Call: _e.mock.On("DeleteElasticIP", ctx, id)}
}

func (_c *ExoscaleClient_DeleteElasticIP_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_DeleteElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_DeleteElasticIP_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_DeleteElasticIP_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_DeleteElasticIP_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.Operation, error)) *ExoscaleClient_DeleteElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRuleFromSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) DeleteRuleFromSecurityGroup(ctx context.Context, id v3.UUID, ruleID v3.UUID) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRuleFromSecurityGroup")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.UUID) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id, ruleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.UUID) *v3.Operation); ok {
		r0 = returnFunc(ctx, id, ruleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id, ruleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_DeleteRuleFromSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRuleFromSecurityGroup'
type ExoscaleClient_DeleteRuleFromSecurityGroup_Call struct {
	*mock.Call
}

// DeleteRuleFromSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
//   - ruleID v3.UUID
func (_e *ExoscaleClient_Expecter) DeleteRuleFromSecurityGroup(ctx any, id any, ruleID any) *ExoscaleClient_DeleteRuleFromSecurityGroup_Call {
	return &ExoscaleClient_DeleteRuleFromSecurityGroup_Call{Call: _e.mock.On("DeleteRuleFromSecurityGroup", ctx, id, ruleID)}
}

func (_c *ExoscaleClient_DeleteRuleFromSecurityGroup_Call) Run(run func(ctx context.Context, id v3.UUID, ruleID v3.UUID)) *ExoscaleClient_DeleteRuleFromSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		var arg2 v3.UUID
		if args[2] != nil {
			arg2 = args[2].(v3.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExoscaleClient_DeleteRuleFromSecurityGroup_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_DeleteRuleFromSecurityGroup_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_DeleteRuleFromSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID, ruleID v3.UUID) (*v3.Operation, error)) *ExoscaleClient_DeleteRuleFromSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) DeleteSecurityGroup(ctx context.Context, id v3.UUID) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecurityGroup")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.Operation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_DeleteSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecurityGroup'
type ExoscaleClient_DeleteSecurityGroup_Call struct {
	*mock.Call
}

// DeleteSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) DeleteSecurityGroup(ctx any, id any) *ExoscaleClient_DeleteSecurityGroup_Call {
	return &ExoscaleClient_DeleteSecurityGroup_Call{Call: _e.mock.On("DeleteSecurityGroup", ctx, id)}
}

func (_c *ExoscaleClient_DeleteSecurityGroup_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_DeleteSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_DeleteSecurityGroup_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_DeleteSecurityGroup_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_DeleteSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.Operation, error)) *ExoscaleClient_DeleteSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetElasticIP provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) GetElasticIP(ctx context.Context, id v3.UUID) (*v3.ElasticIP, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetElasticIP")
	}

	var r0 *v3.ElasticIP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.ElasticIP, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.ElasticIP); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.ElasticIP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_GetElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetElasticIP'
type ExoscaleClient_GetElasticIP_Call struct {
	*mock.Call
}

// GetElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) GetElasticIP(ctx any, id any) *ExoscaleClient_GetElasticIP_Call {
	return &ExoscaleClient_GetElasticIP_Call{Call: _e.mock.On("GetElasticIP", ctx, id)}
}

func (_c *ExoscaleClient_GetElasticIP_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_GetElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_GetElasticIP_Call) Return(elasticIP *v3.ElasticIP, err error) *ExoscaleClient_GetElasticIP_Call {
	_c.Call.Return(elasticIP, err)
	return _c
}

func (_c *ExoscaleClient_GetElasticIP_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.ElasticIP, error)) *ExoscaleClient_GetElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) GetSecurityGroup(ctx context.Context, id v3.UUID) (*v3.SecurityGroup, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSecurityGroup")
	}

	var r0 *v3.SecurityGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.SecurityGroup, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.SecurityGroup); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.SecurityGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_GetSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecurityGroup'
type ExoscaleClient_GetSecurityGroup_Call struct {
	*mock.Call
}

// GetSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) GetSecurityGroup(ctx any, id any) *ExoscaleClient_GetSecurityGroup_Call {
	return &ExoscaleClient_GetSecurityGroup_Call{Call: _e.mock.On("GetSecurityGroup", ctx, id)}
}

func (_c *ExoscaleClient_GetSecurityGroup_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_GetSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_GetSecurityGroup_Call) Return(securityGroup *v3.SecurityGroup, err error) *ExoscaleClient_GetSecurityGroup_Call {
	_c.Call.Return(securityGroup, err)
	return _c
}

func (_c *ExoscaleClient_GetSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.SecurityGroup, error)) *ExoscaleClient_GetSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateElasticIP provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) UpdateElasticIP(ctx context.Context, id v3.UUID, req v3.UpdateElasticIPRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateElasticIP")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.UpdateElasticIPRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.UpdateElasticIPRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID, v3.UpdateElasticIPRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_UpdateElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateElasticIP'
type ExoscaleClient_UpdateElasticIP_Call struct {
	*mock.Call
}

// UpdateElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
//   - req v3.UpdateElasticIPRequest
func (_e *ExoscaleClient_Expecter) UpdateElasticIP(ctx any, id any, req any) *ExoscaleClient_UpdateElasticIP_Call {
	return &ExoscaleClient_UpdateElasticIP_Call{Call: _e.mock.On("UpdateElasticIP", ctx, id, req)}
}

func (_c *ExoscaleClient_UpdateElasticIP_Call) Run(run func(ctx context.Context, id v3.UUID, req v3.UpdateElasticIPRequest)) *ExoscaleClient_UpdateElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		var arg2 v3.UpdateElasticIPRequest
		if args[2] != nil {
			arg2 = args[2].(v3.UpdateElasticIPRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExoscaleClient_UpdateElasticIP_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_UpdateElasticIP_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_UpdateElasticIP_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID, req v3.UpdateElasticIPRequest) (*v3.Operation, error)) *ExoscaleClient_UpdateElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) Wait(ctx context.Context, op *v3.Operation, states ...v3.OperationState) (*v3.Operation, error) {
	var tmpRet mock.Arguments
	if len(states) > 0 {
		tmpRet = _mock.Called(ctx, op, states)
	} else {
		tmpRet = _mock.Called(ctx, op)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v3.Operation, ...v3.OperationState) (*v3.Operation, error)); ok {
		return returnFunc(ctx, op, states...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v3.Operation, ...v3.OperationState) *v3.Operation); ok {
		r0 = returnFunc(ctx, op, states...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v3.Operation, ...v3.OperationState) error); ok {
		r1 = returnFunc(ctx, op, states...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type ExoscaleClient_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
//   - op *v3.Operation
//   - states ...v3.OperationState
func (_e *ExoscaleClient_Expecter) Wait(ctx any, op any, states ...any) *ExoscaleClient_Wait_Call {
	return &ExoscaleClient_Wait_Call{Call: _e.mock.On("Wait",
		append([]any{ctx, op}, states...)...)}
}

func (_c *ExoscaleClient_Wait_Call) Run(run func(ctx context.Context, op *v3.Operation, states ...v3.OperationState)) *ExoscaleClient_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v3.Operation
		if args[1] != nil {
			arg1 = args[1].(*v3.Operation)
		}
		var arg2 []v3.OperationState
		var variadicArgs []v3.OperationState
		if len(args) > 2 {
			variadicArgs = args[2].([]v3.OperationState)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ExoscaleClient_Wait_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_Wait_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_Wait_Call) RunAndReturn(run func(ctx context.Context, op *v3.Operation, states ...v3.OperationState) (*v3.Operation, error)) *ExoscaleClient_Wait_Call {
	_c.Call.Return(run)
	return _c
}
