// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/exoscale/egoscale/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewExoscaleClient creates a new instance of ExoscaleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExoscaleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExoscaleClient {
	mock := &ExoscaleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExoscaleClient is an autogenerated mock type for the ExoscaleClient type
type ExoscaleClient struct {
	mock.Mock
}

type ExoscaleClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ExoscaleClient) EXPECT() *ExoscaleClient_Expecter {
	return &ExoscaleClient_Expecter{mock: &_m.Mock}
}

// AddRuleToSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) AddRuleToSecurityGroup(ctx context.Context, id v3.UUID, req v3.AddRuleToSecurityGroupRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for AddRuleToSecurityGroup")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.AddRuleToSecurityGroupRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.AddRuleToSecurityGroupRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID, v3.AddRuleToSecurityGroupRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_AddRuleToSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRuleToSecurityGroup'
type ExoscaleClient_AddRuleToSecurityGroup_Call struct {
	*mock.Call
}

// AddRuleToSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
//   - req v3.AddRuleToSecurityGroupRequest
func (_e *ExoscaleClient_Expecter) AddRuleToSecurityGroup(ctx any, id any, req any) *ExoscaleClient_AddRuleToSecurityGroup_Call {
	return &ExoscaleClient_AddRuleToSecurityGroup_Call{Call: _e.mock.On("AddRuleToSecurityGroup", ctx, id, req)}
}

func (_c *ExoscaleClient_AddRuleToSecurityGroup_Call) Run(run func(ctx context.Context, id v3.UUID, req v3.AddRuleToSecurityGroupRequest)) *ExoscaleClient_AddRuleToSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		var arg2 v3.AddRuleToSecurityGroupRequest
		if args[2] != nil {
			arg2 = args[2].(v3.AddRuleToSecurityGroupRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExoscaleClient_AddRuleToSecurityGroup_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_AddRuleToSecurityGroup_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_AddRuleToSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID, req v3.AddRuleToSecurityGroupRequest) (*v3.Operation, error)) *ExoscaleClient_AddRuleToSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// AttachInstanceToElasticIP provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) AttachInstanceToElasticIP(ctx context.Context, id v3.UUID, req v3.AttachInstanceToElasticIPRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for AttachInstanceToElasticIP")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.AttachInstanceToElasticIPRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.AttachInstanceToElasticIPRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID, v3.AttachInstanceToElasticIPRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_AttachInstanceToElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachInstanceToElasticIP'
type ExoscaleClient_AttachInstanceToElasticIP_Call struct {
	*mock.Call
}

// AttachInstanceToElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
//   - req v3.AttachInstanceToElasticIPRequest
func (_e *ExoscaleClient_Expecter) AttachInstanceToElasticIP(ctx any, id any, req any) *ExoscaleClient_AttachInstanceToElasticIP_Call {
	return &ExoscaleClient_AttachInstanceToElasticIP_Call{Call: _e.mock.On("AttachInstanceToElasticIP", ctx, id, req)}
}

func (_c *ExoscaleClient_AttachInstanceToElasticIP_Call) Run(run func(ctx context.Context, id v3.UUID, req v3.AttachInstanceToElasticIPRequest)) *ExoscaleClient_AttachInstanceToElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		var arg2 v3.AttachInstanceToElasticIPRequest
		if args[2] != nil {
			arg2 = args[2].(v3.AttachInstanceToElasticIPRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExoscaleClient_AttachInstanceToElasticIP_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_AttachInstanceToElasticIP_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_AttachInstanceToElasticIP_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID, req v3.AttachInstanceToElasticIPRequest) (*v3.Operation, error)) *ExoscaleClient_AttachInstanceToElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// AttachInstanceToSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) AttachInstanceToSecurityGroup(ctx context.Context, id v3.UUID, req v3.AttachInstanceToSecurityGroupRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for AttachInstanceToSecurityGroup")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.AttachInstanceToSecurityGroupRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.AttachInstanceToSecurityGroupRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID, v3.AttachInstanceToSecurityGroupRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_AttachInstanceToSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachInstanceToSecurityGroup'
type ExoscaleClient_AttachInstanceToSecurityGroup_Call struct {
	*mock.Call
}

// AttachInstanceToSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
//   - req v3.AttachInstanceToSecurityGroupRequest
func (_e *ExoscaleClient_Expecter) AttachInstanceToSecurityGroup(ctx any, id any, req any) *ExoscaleClient_AttachInstanceToSecurityGroup_Call {
	return &ExoscaleClient_AttachInstanceToSecurityGroup_Call{Call: _e.mock.On("AttachInstanceToSecurityGroup", ctx, id, req)}
}

func (_c *ExoscaleClient_AttachInstanceToSecurityGroup_Call) Run(run func(ctx context.Context, id v3.UUID, req v3.AttachInstanceToSecurityGroupRequest)) *ExoscaleClient_AttachInstanceToSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		var arg2 v3.AttachInstanceToSecurityGroupRequest
		if args[2] != nil {
			arg2 = args[2].(v3.AttachInstanceToSecurityGroupRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExoscaleClient_AttachInstanceToSecurityGroup_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_AttachInstanceToSecurityGroup_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_AttachInstanceToSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID, req v3.AttachInstanceToSecurityGroupRequest) (*v3.Operation, error)) *ExoscaleClient_AttachInstanceToSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateElasticIP provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) CreateElasticIP(ctx context.Context, req v3.CreateElasticIPRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateElasticIP")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateElasticIPRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateElasticIPRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.CreateElasticIPRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_CreateElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateElasticIP'
type ExoscaleClient_CreateElasticIP_Call struct {
	*mock.Call
}

// CreateElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - req v3.CreateElasticIPRequest
func (_e *ExoscaleClient_Expecter) CreateElasticIP(ctx any, req any) *ExoscaleClient_CreateElasticIP_Call {
	return &ExoscaleClient_CreateElasticIP_Call{Call: _e.mock.On("CreateElasticIP", ctx, req)}
}

func (_c *ExoscaleClient_CreateElasticIP_Call) Run(run func(ctx context.Context, req v3.CreateElasticIPRequest)) *ExoscaleClient_CreateElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.CreateElasticIPRequest
		if args[1] != nil {
			arg1 = args[1].(v3.CreateElasticIPRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_CreateElasticIP_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_CreateElasticIP_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_CreateElasticIP_Call) RunAndReturn(run func(ctx context.Context, req v3.CreateElasticIPRequest) (*v3.Operation, error)) *ExoscaleClient_CreateElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInstance provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) CreateInstance(ctx context.Context, req v3.CreateInstanceRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstance")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateInstanceRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateInstanceRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.CreateInstanceRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_CreateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstance'
type ExoscaleClient_CreateInstance_Call struct {
	*mock.Call
}

// CreateInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - req v3.CreateInstanceRequest
func (_e *ExoscaleClient_Expecter) CreateInstance(ctx any, req any) *ExoscaleClient_CreateInstance_Call {
	return &ExoscaleClient_CreateInstance_Call{Call: _e.mock.On("CreateInstance", ctx, req)}
}

func (_c *ExoscaleClient_CreateInstance_Call) Run(run func(ctx context.Context, req v3.CreateInstanceRequest)) *ExoscaleClient_CreateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.CreateInstanceRequest
		if args[1] != nil {
			arg1 = args[1].(v3.CreateInstanceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_CreateInstance_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_CreateInstance_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_CreateInstance_Call) RunAndReturn(run func(ctx context.Context, req v3.CreateInstanceRequest) (*v3.Operation, error)) *ExoscaleClient_CreateInstance_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) CreateSecurityGroup(ctx context.Context, req v3.CreateSecurityGroupRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecurityGroup")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateSecurityGroupRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateSecurityGroupRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.CreateSecurityGroupRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_CreateSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecurityGroup'
type ExoscaleClient_CreateSecurityGroup_Call struct {
	*mock.Call
}

// CreateSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - req v3.CreateSecurityGroupRequest
func (_e *ExoscaleClient_Expecter) CreateSecurityGroup(ctx any, req any) *ExoscaleClient_CreateSecurityGroup_Call {
	return &ExoscaleClient_CreateSecurityGroup_Call{Call: _e.mock.On("CreateSecurityGroup", ctx, req)}
}

func (_c *ExoscaleClient_CreateSecurityGroup_Call) Run(run func(ctx context.Context, req v3.CreateSecurityGroupRequest)) *ExoscaleClient_CreateSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.CreateSecurityGroupRequest
		if args[1] != nil {
			arg1 = args[1].(v3.CreateSecurityGroupRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_CreateSecurityGroup_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_CreateSecurityGroup_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_CreateSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, req v3.CreateSecurityGroupRequest) (*v3.Operation, error)) *ExoscaleClient_CreateSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteElasticIP provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) DeleteElasticIP(ctx context.Context, id v3.UUID) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteElasticIP")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.Operation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_DeleteElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteElasticIP'
type ExoscaleClient_DeleteElasticIP_Call struct {
	*mock.Call
}

// DeleteElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) DeleteElasticIP(ctx any, id any) *ExoscaleClient_DeleteElasticIP_Call {
	return &ExoscaleClient_DeleteElasticIP_Call{Call: _e.mock.On("DeleteElasticIP", ctx, id)}
}

func (_c *ExoscaleClient_DeleteElasticIP_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_DeleteElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_DeleteElasticIP_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_DeleteElasticIP_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_DeleteElasticIP_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.Operation, error)) *ExoscaleClient_DeleteElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInstance provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) DeleteInstance(ctx context.Context, id v3.UUID) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInstance")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.Operation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_DeleteInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInstance'
type ExoscaleClient_DeleteInstance_Call struct {
	*mock.Call
}

// DeleteInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) DeleteInstance(ctx any, id any) *ExoscaleClient_DeleteInstance_Call {
	return &ExoscaleClient_DeleteInstance_Call{Call: _e.mock.On("DeleteInstance", ctx, id)}
}

func (_c *ExoscaleClient_DeleteInstance_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_DeleteInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_DeleteInstance_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_DeleteInstance_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_DeleteInstance_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.Operation, error)) *ExoscaleClient_DeleteInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRuleFromSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) DeleteRuleFromSecurityGroup(ctx context.Context, id v3.UUID, ruleID v3.UUID) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRuleFromSecurityGroup")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.UUID) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id, ruleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.UUID) *v3.Operation); ok {
		r0 = returnFunc(ctx, id, ruleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id, ruleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_DeleteRuleFromSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRuleFromSecurityGroup'
type ExoscaleClient_DeleteRuleFromSecurityGroup_Call struct {
	*mock.Call
}

// DeleteRuleFromSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
//   - ruleID v3.UUID
func (_e *ExoscaleClient_Expecter) DeleteRuleFromSecurityGroup(ctx any, id any, ruleID any) *ExoscaleClient_DeleteRuleFromSecurityGroup_Call {
	return &ExoscaleClient_DeleteRuleFromSecurityGroup_Call{Call: _e.mock.On("DeleteRuleFromSecurityGroup", ctx, id, ruleID)}
}

func (_c *ExoscaleClient_DeleteRuleFromSecurityGroup_Call) Run(run func(ctx context.Context, id v3.UUID, ruleID v3.UUID)) *ExoscaleClient_DeleteRuleFromSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		var arg2 v3.UUID
		if args[2] != nil {
			arg2 = args[2].(v3.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExoscaleClient_DeleteRuleFromSecurityGroup_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_DeleteRuleFromSecurityGroup_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_DeleteRuleFromSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID, ruleID v3.UUID) (*v3.Operation, error)) *ExoscaleClient_DeleteRuleFromSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) DeleteSecurityGroup(ctx context.Context, id v3.UUID) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecurityGroup")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.Operation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_DeleteSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecurityGroup'
type ExoscaleClient_DeleteSecurityGroup_Call struct {
	*mock.Call
}

// DeleteSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) DeleteSecurityGroup(ctx any, id any) *ExoscaleClient_DeleteSecurityGroup_Call {
	return &ExoscaleClient_DeleteSecurityGroup_Call{Call: _e.mock.On("DeleteSecurityGroup", ctx, id)}
}

func (_c *ExoscaleClient_DeleteSecurityGroup_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_DeleteSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_DeleteSecurityGroup_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_DeleteSecurityGroup_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_DeleteSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.Operation, error)) *ExoscaleClient_DeleteSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DetachInstanceFromSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) DetachInstanceFromSecurityGroup(ctx context.Context, id v3.UUID, req v3.DetachInstanceFromSecurityGroupRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for DetachInstanceFromSecurityGroup")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.DetachInstanceFromSecurityGroupRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.DetachInstanceFromSecurityGroupRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID, v3.DetachInstanceFromSecurityGroupRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_DetachInstanceFromSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachInstanceFromSecurityGroup'
type ExoscaleClient_DetachInstanceFromSecurityGroup_Call struct {
	*mock.Call
}

// DetachInstanceFromSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
//   - req v3.DetachInstanceFromSecurityGroupRequest
func (_e *ExoscaleClient_Expecter) DetachInstanceFromSecurityGroup(ctx any, id any, req any) *ExoscaleClient_DetachInstanceFromSecurityGroup_Call {
	return &ExoscaleClient_DetachInstanceFromSecurityGroup_Call{Call: _e.mock.On("DetachInstanceFromSecurityGroup", ctx, id, req)}
}

func (_c *ExoscaleClient_DetachInstanceFromSecurityGroup_Call) Run(run func(ctx context.Context, id v3.UUID, req v3.DetachInstanceFromSecurityGroupRequest)) *ExoscaleClient_DetachInstanceFromSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		var arg2 v3.DetachInstanceFromSecurityGroupRequest
		if args[2] != nil {
			arg2 = args[2].(v3.DetachInstanceFromSecurityGroupRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExoscaleClient_DetachInstanceFromSecurityGroup_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_DetachInstanceFromSecurityGroup_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_DetachInstanceFromSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID, req v3.DetachInstanceFromSecurityGroupRequest) (*v3.Operation, error)) *ExoscaleClient_DetachInstanceFromSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetElasticIP provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) GetElasticIP(ctx context.Context, id v3.UUID) (*v3.ElasticIP, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetElasticIP")
	}

	var r0 *v3.ElasticIP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.ElasticIP, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.ElasticIP); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.ElasticIP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_GetElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetElasticIP'
type ExoscaleClient_GetElasticIP_Call struct {
	*mock.Call
}

// GetElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) GetElasticIP(ctx any, id any) *ExoscaleClient_GetElasticIP_Call {
	return &ExoscaleClient_GetElasticIP_Call{Call: _e.mock.On("GetElasticIP", ctx, id)}
}

func (_c *ExoscaleClient_GetElasticIP_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_GetElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_GetElasticIP_Call) Return(elasticIP *v3.ElasticIP, err error) *ExoscaleClient_GetElasticIP_Call {
	_c.Call.Return(elasticIP, err)
	return _c
}

func (_c *ExoscaleClient_GetElasticIP_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.ElasticIP, error)) *ExoscaleClient_GetElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) GetInstance(ctx context.Context, id v3.UUID) (*v3.Instance, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *v3.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.Instance, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.Instance); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type ExoscaleClient_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) GetInstance(ctx any, id any) *ExoscaleClient_GetInstance_Call {
	return &ExoscaleClient_GetInstance_Call{Call: _e.mock.On("GetInstance", ctx, id)}
}

func (_c *ExoscaleClient_GetInstance_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_GetInstance_Call) Return(instance *v3.Instance, err error) *ExoscaleClient_GetInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *ExoscaleClient_GetInstance_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.Instance, error)) *ExoscaleClient_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecurityGroup provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) GetSecurityGroup(ctx context.Context, id v3.UUID) (*v3.SecurityGroup, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSecurityGroup")
	}

	var r0 *v3.SecurityGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.SecurityGroup, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.SecurityGroup); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.SecurityGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_GetSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecurityGroup'
type ExoscaleClient_GetSecurityGroup_Call struct {
	*mock.Call
}

// GetSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) GetSecurityGroup(ctx any, id any) *ExoscaleClient_GetSecurityGroup_Call {
	return &ExoscaleClient_GetSecurityGroup_Call{Call: _e.mock.On("GetSecurityGroup", ctx, id)}
}

func (_c *ExoscaleClient_GetSecurityGroup_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_GetSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_GetSecurityGroup_Call) Return(securityGroup *v3.SecurityGroup, err error) *ExoscaleClient_GetSecurityGroup_Call {
	_c.Call.Return(securityGroup, err)
	return _c
}

func (_c *ExoscaleClient_GetSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.SecurityGroup, error)) *ExoscaleClient_GetSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) GetTemplate(ctx context.Context, id v3.UUID) (*v3.Template, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 *v3.Template
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.Template, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.Template); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Template)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type ExoscaleClient_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *ExoscaleClient_Expecter) GetTemplate(ctx any, id any) *ExoscaleClient_GetTemplate_Call {
	return &ExoscaleClient_GetTemplate_Call{Call: _e.mock.On("GetTemplate", ctx, id)}
}

func (_c *ExoscaleClient_GetTemplate_Call) Run(run func(ctx context.Context, id v3.UUID)) *ExoscaleClient_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExoscaleClient_GetTemplate_Call) Return(template *v3.Template, err error) *ExoscaleClient_GetTemplate_Call {
	_c.Call.Return(template, err)
	return _c
}

func (_c *ExoscaleClient_GetTemplate_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.Template, error)) *ExoscaleClient_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ListElasticIPS provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) ListElasticIPS(ctx context.Context) (*v3.ListElasticIPSResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListElasticIPS")
	}

	var r0 *v3.ListElasticIPSResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*v3.ListElasticIPSResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *v3.ListElasticIPSResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.ListElasticIPSResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_ListElasticIPS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListElasticIPS'
type ExoscaleClient_ListElasticIPS_Call struct {
	*mock.Call
}

// ListElasticIPS is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ExoscaleClient_Expecter) ListElasticIPS(ctx any) *ExoscaleClient_ListElasticIPS_Call {
	return &ExoscaleClient_ListElasticIPS_Call{Call: _e.mock.On("ListElasticIPS", ctx)}
}

func (_c *ExoscaleClient_ListElasticIPS_Call) Run(run func(ctx context.Context)) *ExoscaleClient_ListElasticIPS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExoscaleClient_ListElasticIPS_Call) Return(listElasticIPSResponse *v3.ListElasticIPSResponse, err error) *ExoscaleClient_ListElasticIPS_Call {
	_c.Call.Return(listElasticIPSResponse, err)
	return _c
}

func (_c *ExoscaleClient_ListElasticIPS_Call) RunAndReturn(run func(ctx context.Context) (*v3.ListElasticIPSResponse, error)) *ExoscaleClient_ListElasticIPS_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstanceTypes provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) ListInstanceTypes(ctx context.Context) (*v3.ListInstanceTypesResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListInstanceTypes")
	}

	var r0 *v3.ListInstanceTypesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*v3.ListInstanceTypesResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *v3.ListInstanceTypesResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.ListInstanceTypesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_ListInstanceTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstanceTypes'
type ExoscaleClient_ListInstanceTypes_Call struct {
	*mock.Call
}

// ListInstanceTypes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ExoscaleClient_Expecter) ListInstanceTypes(ctx any) *ExoscaleClient_ListInstanceTypes_Call {
	return &ExoscaleClient_ListInstanceTypes_Call{Call: _e.mock.On("ListInstanceTypes", ctx)}
}

func (_c *ExoscaleClient_ListInstanceTypes_Call) Run(run func(ctx context.Context)) *ExoscaleClient_ListInstanceTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExoscaleClient_ListInstanceTypes_Call) Return(listInstanceTypesResponse *v3.ListInstanceTypesResponse, err error) *ExoscaleClient_ListInstanceTypes_Call {
	_c.Call.Return(listInstanceTypesResponse, err)
	return _c
}

func (_c *ExoscaleClient_ListInstanceTypes_Call) RunAndReturn(run func(ctx context.Context) (*v3.ListInstanceTypesResponse, error)) *ExoscaleClient_ListInstanceTypes_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstances provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) ListInstances(ctx context.Context, opts ...v3.ListInstancesOpt) (*v3.ListInstancesResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListInstances")
	}

	var r0 *v3.ListInstancesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...v3.ListInstancesOpt) (*v3.ListInstancesResponse, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...v3.ListInstancesOpt) *v3.ListInstancesResponse); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.ListInstancesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...v3.ListInstancesOpt) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_ListInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstances'
type ExoscaleClient_ListInstances_Call struct {
	*mock.Call
}

// ListInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...v3.ListInstancesOpt
func (_e *ExoscaleClient_Expecter) ListInstances(ctx any, opts ...any) *ExoscaleClient_ListInstances_Call {
	return &ExoscaleClient_ListInstances_Call{Call: _e.mock.On("ListInstances",
		append([]any{ctx}, opts...)...)}
}

func (_c *ExoscaleClient_ListInstances_Call) Run(run func(ctx context.Context, opts ...v3.ListInstancesOpt)) *ExoscaleClient_ListInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []v3.ListInstancesOpt
		var variadicArgs []v3.ListInstancesOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]v3.ListInstancesOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ExoscaleClient_ListInstances_Call) Return(listInstancesResponse *v3.ListInstancesResponse, err error) *ExoscaleClient_ListInstances_Call {
	_c.Call.Return(listInstancesResponse, err)
	return _c
}

func (_c *ExoscaleClient_ListInstances_Call) RunAndReturn(run func(ctx context.Context, opts ...v3.ListInstancesOpt) (*v3.ListInstancesResponse, error)) *ExoscaleClient_ListInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecurityGroups provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) ListSecurityGroups(ctx context.Context, opts ...v3.ListSecurityGroupsOpt) (*v3.ListSecurityGroupsResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListSecurityGroups")
	}

	var r0 *v3.ListSecurityGroupsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...v3.ListSecurityGroupsOpt) (*v3.ListSecurityGroupsResponse, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...v3.ListSecurityGroupsOpt) *v3.ListSecurityGroupsResponse); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.ListSecurityGroupsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...v3.ListSecurityGroupsOpt) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_ListSecurityGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecurityGroups'
type ExoscaleClient_ListSecurityGroups_Call struct {
	*mock.Call
}

// ListSecurityGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...v3.ListSecurityGroupsOpt
func (_e *ExoscaleClient_Expecter) ListSecurityGroups(ctx any, opts ...any) *ExoscaleClient_ListSecurityGroups_Call {
	return &ExoscaleClient_ListSecurityGroups_Call{Call: _e.mock.On("ListSecurityGroups",
		append([]any{ctx}, opts...)...)}
}

func (_c *ExoscaleClient_ListSecurityGroups_Call) Run(run func(ctx context.Context, opts ...v3.ListSecurityGroupsOpt)) *ExoscaleClient_ListSecurityGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []v3.ListSecurityGroupsOpt
		var variadicArgs []v3.ListSecurityGroupsOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]v3.ListSecurityGroupsOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ExoscaleClient_ListSecurityGroups_Call) Return(listSecurityGroupsResponse *v3.ListSecurityGroupsResponse, err error) *ExoscaleClient_ListSecurityGroups_Call {
	_c.Call.Return(listSecurityGroupsResponse, err)
	return _c
}

func (_c *ExoscaleClient_ListSecurityGroups_Call) RunAndReturn(run func(ctx context.Context, opts ...v3.ListSecurityGroupsOpt) (*v3.ListSecurityGroupsResponse, error)) *ExoscaleClient_ListSecurityGroups_Call {
	_c.Call.Return(run)
	return _c
}

// ListTemplates provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) ListTemplates(ctx context.Context, opts ...v3.ListTemplatesOpt) (*v3.ListTemplatesResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListTemplates")
	}

	var r0 *v3.ListTemplatesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...v3.ListTemplatesOpt) (*v3.ListTemplatesResponse, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...v3.ListTemplatesOpt) *v3.ListTemplatesResponse); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.ListTemplatesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...v3.ListTemplatesOpt) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_ListTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTemplates'
type ExoscaleClient_ListTemplates_Call struct {
	*mock.Call
}

// ListTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...v3.ListTemplatesOpt
func (_e *ExoscaleClient_Expecter) ListTemplates(ctx any, opts ...any) *ExoscaleClient_ListTemplates_Call {
	return &ExoscaleClient_ListTemplates_Call{Call: _e.mock.On("ListTemplates",
		append([]any{ctx}, opts...)...)}
}

func (_c *ExoscaleClient_ListTemplates_Call) Run(run func(ctx context.Context, opts ...v3.ListTemplatesOpt)) *ExoscaleClient_ListTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []v3.ListTemplatesOpt
		var variadicArgs []v3.ListTemplatesOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]v3.ListTemplatesOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ExoscaleClient_ListTemplates_Call) Return(listTemplatesResponse *v3.ListTemplatesResponse, err error) *ExoscaleClient_ListTemplates_Call {
	_c.Call.Return(listTemplatesResponse, err)
	return _c
}

func (_c *ExoscaleClient_ListTemplates_Call) RunAndReturn(run func(ctx context.Context, opts ...v3.ListTemplatesOpt) (*v3.ListTemplatesResponse, error)) *ExoscaleClient_ListTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateElasticIP provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) UpdateElasticIP(ctx context.Context, id v3.UUID, req v3.UpdateElasticIPRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateElasticIP")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.UpdateElasticIPRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID, v3.UpdateElasticIPRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID, v3.UpdateElasticIPRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_UpdateElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateElasticIP'
type ExoscaleClient_UpdateElasticIP_Call struct {
	*mock.Call
}

// UpdateElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
//   - req v3.UpdateElasticIPRequest
func (_e *ExoscaleClient_Expecter) UpdateElasticIP(ctx any, id any, req any) *ExoscaleClient_UpdateElasticIP_Call {
	return &ExoscaleClient_UpdateElasticIP_Call{Call: _e.mock.On("UpdateElasticIP", ctx, id, req)}
}

func (_c *ExoscaleClient_UpdateElasticIP_Call) Run(run func(ctx context.Context, id v3.UUID, req v3.UpdateElasticIPRequest)) *ExoscaleClient_UpdateElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		var arg2 v3.UpdateElasticIPRequest
		if args[2] != nil {
			arg2 = args[2].(v3.UpdateElasticIPRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ExoscaleClient_UpdateElasticIP_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_UpdateElasticIP_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_UpdateElasticIP_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID, req v3.UpdateElasticIPRequest) (*v3.Operation, error)) *ExoscaleClient_UpdateElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type ExoscaleClient
func (_mock *ExoscaleClient) Wait(ctx context.Context, op *v3.Operation, states ...v3.OperationState) (*v3.Operation, error) {
	var tmpRet mock.Arguments
	if len(states) > 0 {
		tmpRet = _mock.Called(ctx, op, states)
	} else {
		tmpRet = _mock.Called(ctx, op)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v3.Operation, ...v3.OperationState) (*v3.Operation, error)); ok {
		return returnFunc(ctx, op, states...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v3.Operation, ...v3.OperationState) *v3.Operation); ok {
		r0 = returnFunc(ctx, op, states...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v3.Operation, ...v3.OperationState) error); ok {
		r1 = returnFunc(ctx, op, states...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExoscaleClient_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type ExoscaleClient_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
//   - op *v3.Operation
//   - states ...v3.OperationState
func (_e *ExoscaleClient_Expecter) Wait(ctx any, op any, states ...any) *ExoscaleClient_Wait_Call {
	return &ExoscaleClient_Wait_Call{Call: _e.mock.On("Wait",
		append([]any{ctx, op}, states...)...)}
}

func (_c *ExoscaleClient_Wait_Call) Run(run func(ctx context.Context, op *v3.Operation, states ...v3.OperationState)) *ExoscaleClient_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v3.Operation
		if args[1] != nil {
			arg1 = args[1].(*v3.Operation)
		}
		var arg2 []v3.OperationState
		var variadicArgs []v3.OperationState
		if len(args) > 2 {
			variadicArgs = args[2].([]v3.OperationState)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ExoscaleClient_Wait_Call) Return(operation *v3.Operation, err error) *ExoscaleClient_Wait_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *ExoscaleClient_Wait_Call) RunAndReturn(run func(ctx context.Context, op *v3.Operation, states ...v3.OperationState) (*v3.Operation, error)) *ExoscaleClient_Wait_Call {
	_c.Call.Return(run)
	return _c
}
