// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/exoscale/cluster-api-provider-exoscale/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewInstanceService creates a new instance of InstanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InstanceService {
	mock := &InstanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InstanceService is an autogenerated mock type for the InstanceService type
type InstanceService struct {
	mock.Mock
}

type InstanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *InstanceService) EXPECT() *InstanceService_Expecter {
	return &InstanceService_Expecter{mock: &_m.Mock}
}

// DeleteInstance provides a mock function for the type InstanceService
func (_mock *InstanceService) DeleteInstance(ctx context.Context, machineID *domain.MachineID, clusterID uuid.UUID, instanceID *uuid.UUID) error {
	ret := _mock.Called(ctx, machineID, clusterID, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MachineID, uuid.UUID, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, machineID, clusterID, instanceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InstanceService_DeleteInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInstance'
type InstanceService_DeleteInstance_Call struct {
	*mock.Call
}

// DeleteInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - machineID *domain.MachineID
//   - clusterID uuid.UUID
//   - instanceID *uuid.UUID
func (_e *InstanceService_Expecter) DeleteInstance(ctx any, machineID any, clusterID any, instanceID any) *InstanceService_DeleteInstance_Call {
	return &InstanceService_DeleteInstance_Call{Call: _e.mock.On("DeleteInstance", ctx, machineID, clusterID, instanceID)}
}

func (_c *InstanceService_DeleteInstance_Call) Run(run func(ctx context.Context, machineID *domain.MachineID, clusterID uuid.UUID, instanceID *uuid.UUID)) *InstanceService_DeleteInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.MachineID
		if args[1] != nil {
			arg1 = args[1].(*domain.MachineID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *InstanceService_DeleteInstance_Call) Return(err error) *InstanceService_DeleteInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InstanceService_DeleteInstance_Call) RunAndReturn(run func(ctx context.Context, machineID *domain.MachineID, clusterID uuid.UUID, instanceID *uuid.UUID) error) *InstanceService_DeleteInstance_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertInstance provides a mock function for the type InstanceService
func (_mock *InstanceService) UpsertInstance(ctx context.Context, machineID domain.MachineID, instanceID *uuid.UUID, spec domain.InstanceSpec) (domain.Instance, error) {
	ret := _mock.Called(ctx, machineID, instanceID, spec)

	if len(ret) == 0 {
		panic("no return value specified for UpsertInstance")
	}

	var r0 domain.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.MachineID, *uuid.UUID, domain.InstanceSpec) (domain.Instance, error)); ok {
		return returnFunc(ctx, machineID, instanceID, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.MachineID, *uuid.UUID, domain.InstanceSpec) domain.Instance); ok {
		r0 = returnFunc(ctx, machineID, instanceID, spec)
	} else {
		r0 = ret.Get(0).(domain.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.MachineID, *uuid.UUID, domain.InstanceSpec) error); ok {
		r1 = returnFunc(ctx, machineID, instanceID, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceService_UpsertInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertInstance'
type InstanceService_UpsertInstance_Call struct {
	*mock.Call
}

// UpsertInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - machineID domain.MachineID
//   - instanceID *uuid.UUID
//   - spec domain.InstanceSpec
func (_e *InstanceService_Expecter) UpsertInstance(ctx any, machineID any, instanceID any, spec any) *InstanceService_UpsertInstance_Call {
	return &InstanceService_UpsertInstance_Call{Call: _e.mock.On("UpsertInstance", ctx, machineID, instanceID, spec)}
}

func (_c *InstanceService_UpsertInstance_Call) Run(run func(ctx context.Context, machineID domain.MachineID, instanceID *uuid.UUID, spec domain.InstanceSpec)) *InstanceService_UpsertInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.MachineID
		if args[1] != nil {
			arg1 = args[1].(domain.MachineID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		var arg3 domain.InstanceSpec
		if args[3] != nil {
			arg3 = args[3].(domain.InstanceSpec)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *InstanceService_UpsertInstance_Call) Return(instance domain.Instance, err error) *InstanceService_UpsertInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *InstanceService_UpsertInstance_Call) RunAndReturn(run func(ctx context.Context, machineID domain.MachineID, instanceID *uuid.UUID, spec domain.InstanceSpec) (domain.Instance, error)) *InstanceService_UpsertInstance_Call {
	_c.Call.Return(run)
	return _c
}
