// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/exoscale/egoscale/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewInstanceClient creates a new instance of InstanceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstanceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InstanceClient {
	mock := &InstanceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InstanceClient is an autogenerated mock type for the instanceClient type
type InstanceClient struct {
	mock.Mock
}

type InstanceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InstanceClient) EXPECT() *InstanceClient_Expecter {
	return &InstanceClient_Expecter{mock: &_m.Mock}
}

// CreateInstance provides a mock function for the type InstanceClient
func (_mock *InstanceClient) CreateInstance(ctx context.Context, req v3.CreateInstanceRequest) (*v3.Operation, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstance")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateInstanceRequest) (*v3.Operation, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.CreateInstanceRequest) *v3.Operation); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.CreateInstanceRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceClient_CreateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstance'
type InstanceClient_CreateInstance_Call struct {
	*mock.Call
}

// CreateInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - req v3.CreateInstanceRequest
func (_e *InstanceClient_Expecter) CreateInstance(ctx any, req any) *InstanceClient_CreateInstance_Call {
	return &InstanceClient_CreateInstance_Call{Call: _e.mock.On("CreateInstance", ctx, req)}
}

func (_c *InstanceClient_CreateInstance_Call) Run(run func(ctx context.Context, req v3.CreateInstanceRequest)) *InstanceClient_CreateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.CreateInstanceRequest
		if args[1] != nil {
			arg1 = args[1].(v3.CreateInstanceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InstanceClient_CreateInstance_Call) Return(operation *v3.Operation, err error) *InstanceClient_CreateInstance_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *InstanceClient_CreateInstance_Call) RunAndReturn(run func(ctx context.Context, req v3.CreateInstanceRequest) (*v3.Operation, error)) *InstanceClient_CreateInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInstance provides a mock function for the type InstanceClient
func (_mock *InstanceClient) DeleteInstance(ctx context.Context, id v3.UUID) (*v3.Operation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInstance")
	}

	var r0 *v3.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.Operation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.Operation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceClient_DeleteInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInstance'
type InstanceClient_DeleteInstance_Call struct {
	*mock.Call
}

// DeleteInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *InstanceClient_Expecter) DeleteInstance(ctx any, id any) *InstanceClient_DeleteInstance_Call {
	return &InstanceClient_DeleteInstance_Call{Call: _e.mock.On("DeleteInstance", ctx, id)}
}

func (_c *InstanceClient_DeleteInstance_Call) Run(run func(ctx context.Context, id v3.UUID)) *InstanceClient_DeleteInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InstanceClient_DeleteInstance_Call) Return(operation *v3.Operation, err error) *InstanceClient_DeleteInstance_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *InstanceClient_DeleteInstance_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.Operation, error)) *InstanceClient_DeleteInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type InstanceClient
func (_mock *InstanceClient) GetInstance(ctx context.Context, id v3.UUID) (*v3.Instance, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *v3.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.Instance, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.Instance); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceClient_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type InstanceClient_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *InstanceClient_Expecter) GetInstance(ctx any, id any) *InstanceClient_GetInstance_Call {
	return &InstanceClient_GetInstance_Call{Call: _e.mock.On("GetInstance", ctx, id)}
}

func (_c *InstanceClient_GetInstance_Call) Run(run func(ctx context.Context, id v3.UUID)) *InstanceClient_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InstanceClient_GetInstance_Call) Return(instance *v3.Instance, err error) *InstanceClient_GetInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *InstanceClient_GetInstance_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.Instance, error)) *InstanceClient_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function for the type InstanceClient
func (_mock *InstanceClient) GetTemplate(ctx context.Context, id v3.UUID) (*v3.Template, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 *v3.Template
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) (*v3.Template, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v3.UUID) *v3.Template); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.Template)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v3.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceClient_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type InstanceClient_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id v3.UUID
func (_e *InstanceClient_Expecter) GetTemplate(ctx any, id any) *InstanceClient_GetTemplate_Call {
	return &InstanceClient_GetTemplate_Call{Call: _e.mock.On("GetTemplate", ctx, id)}
}

func (_c *InstanceClient_GetTemplate_Call) Run(run func(ctx context.Context, id v3.UUID)) *InstanceClient_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v3.UUID
		if args[1] != nil {
			arg1 = args[1].(v3.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InstanceClient_GetTemplate_Call) Return(template *v3.Template, err error) *InstanceClient_GetTemplate_Call {
	_c.Call.Return(template, err)
	return _c
}

func (_c *InstanceClient_GetTemplate_Call) RunAndReturn(run func(ctx context.Context, id v3.UUID) (*v3.Template, error)) *InstanceClient_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstanceTypes provides a mock function for the type InstanceClient
func (_mock *InstanceClient) ListInstanceTypes(ctx context.Context) (*v3.ListInstanceTypesResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListInstanceTypes")
	}

	var r0 *v3.ListInstanceTypesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*v3.ListInstanceTypesResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *v3.ListInstanceTypesResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.ListInstanceTypesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceClient_ListInstanceTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstanceTypes'
type InstanceClient_ListInstanceTypes_Call struct {
	*mock.Call
}

// ListInstanceTypes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *InstanceClient_Expecter) ListInstanceTypes(ctx any) *InstanceClient_ListInstanceTypes_Call {
	return &InstanceClient_ListInstanceTypes_Call{Call: _e.mock.On("ListInstanceTypes", ctx)}
}

func (_c *InstanceClient_ListInstanceTypes_Call) Run(run func(ctx context.Context)) *InstanceClient_ListInstanceTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *InstanceClient_ListInstanceTypes_Call) Return(listInstanceTypesResponse *v3.ListInstanceTypesResponse, err error) *InstanceClient_ListInstanceTypes_Call {
	_c.Call.Return(listInstanceTypesResponse, err)
	return _c
}

func (_c *InstanceClient_ListInstanceTypes_Call) RunAndReturn(run func(ctx context.Context) (*v3.ListInstanceTypesResponse, error)) *InstanceClient_ListInstanceTypes_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstances provides a mock function for the type InstanceClient
func (_mock *InstanceClient) ListInstances(ctx context.Context, opts ...v3.ListInstancesOpt) (*v3.ListInstancesResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListInstances")
	}

	var r0 *v3.ListInstancesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...v3.ListInstancesOpt) (*v3.ListInstancesResponse, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...v3.ListInstancesOpt) *v3.ListInstancesResponse); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.ListInstancesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...v3.ListInstancesOpt) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceClient_ListInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstances'
type InstanceClient_ListInstances_Call struct {
	*mock.Call
}

// ListInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...v3.ListInstancesOpt
func (_e *InstanceClient_Expecter) ListInstances(ctx any, opts ...any) *InstanceClient_ListInstances_Call {
	return &InstanceClient_ListInstances_Call{Call: _e.mock.On("ListInstances",
		append([]any{ctx}, opts...)...)}
}

func (_c *InstanceClient_ListInstances_Call) Run(run func(ctx context.Context, opts ...v3.ListInstancesOpt)) *InstanceClient_ListInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []v3.ListInstancesOpt
		var variadicArgs []v3.ListInstancesOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]v3.ListInstancesOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *InstanceClient_ListInstances_Call) Return(listInstancesResponse *v3.ListInstancesResponse, err error) *InstanceClient_ListInstances_Call {
	_c.Call.Return(listInstancesResponse, err)
	return _c
}

func (_c *InstanceClient_ListInstances_Call) RunAndReturn(run func(ctx context.Context, opts ...v3.ListInstancesOpt) (*v3.ListInstancesResponse, error)) *InstanceClient_ListInstances_Call {
	_c.Call.Return(run)
	return _c
}
