// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/exoscale/cluster-api-provider-exoscale/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewInstanceCloud creates a new instance of InstanceCloud. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstanceCloud(t interface {
	mock.TestingT
	Cleanup(func())
}) *InstanceCloud {
	mock := &InstanceCloud{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InstanceCloud is an autogenerated mock type for the instanceCloud type
type InstanceCloud struct {
	mock.Mock
}

type InstanceCloud_Expecter struct {
	mock *mock.Mock
}

func (_m *InstanceCloud) EXPECT() *InstanceCloud_Expecter {
	return &InstanceCloud_Expecter{mock: &_m.Mock}
}

// AttachInstanceToElasticIP provides a mock function for the type InstanceCloud
func (_mock *InstanceCloud) AttachInstanceToElasticIP(ctx context.Context, instanceID uuid.UUID, elasticIPID uuid.UUID) error {
	ret := _mock.Called(ctx, instanceID, elasticIPID)

	if len(ret) == 0 {
		panic("no return value specified for AttachInstanceToElasticIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, instanceID, elasticIPID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InstanceCloud_AttachInstanceToElasticIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachInstanceToElasticIP'
type InstanceCloud_AttachInstanceToElasticIP_Call struct {
	*mock.Call
}

// AttachInstanceToElasticIP is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID uuid.UUID
//   - elasticIPID uuid.UUID
func (_e *InstanceCloud_Expecter) AttachInstanceToElasticIP(ctx any, instanceID any, elasticIPID any) *InstanceCloud_AttachInstanceToElasticIP_Call {
	return &InstanceCloud_AttachInstanceToElasticIP_Call{Call: _e.mock.On("AttachInstanceToElasticIP", ctx, instanceID, elasticIPID)}
}

func (_c *InstanceCloud_AttachInstanceToElasticIP_Call) Run(run func(ctx context.Context, instanceID uuid.UUID, elasticIPID uuid.UUID)) *InstanceCloud_AttachInstanceToElasticIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InstanceCloud_AttachInstanceToElasticIP_Call) Return(err error) *InstanceCloud_AttachInstanceToElasticIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InstanceCloud_AttachInstanceToElasticIP_Call) RunAndReturn(run func(ctx context.Context, instanceID uuid.UUID, elasticIPID uuid.UUID) error) *InstanceCloud_AttachInstanceToElasticIP_Call {
	_c.Call.Return(run)
	return _c
}

// AttachInstanceToSecurityGroup provides a mock function for the type InstanceCloud
func (_mock *InstanceCloud) AttachInstanceToSecurityGroup(ctx context.Context, instanceID uuid.UUID, securityGroupID uuid.UUID) error {
	ret := _mock.Called(ctx, instanceID, securityGroupID)

	if len(ret) == 0 {
		panic("no return value specified for AttachInstanceToSecurityGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, instanceID, securityGroupID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InstanceCloud_AttachInstanceToSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachInstanceToSecurityGroup'
type InstanceCloud_AttachInstanceToSecurityGroup_Call struct {
	*mock.Call
}

// AttachInstanceToSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID uuid.UUID
//   - securityGroupID uuid.UUID
func (_e *InstanceCloud_Expecter) AttachInstanceToSecurityGroup(ctx any, instanceID any, securityGroupID any) *InstanceCloud_AttachInstanceToSecurityGroup_Call {
	return &InstanceCloud_AttachInstanceToSecurityGroup_Call{Call: _e.mock.On("AttachInstanceToSecurityGroup", ctx, instanceID, securityGroupID)}
}

func (_c *InstanceCloud_AttachInstanceToSecurityGroup_Call) Run(run func(ctx context.Context, instanceID uuid.UUID, securityGroupID uuid.UUID)) *InstanceCloud_AttachInstanceToSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InstanceCloud_AttachInstanceToSecurityGroup_Call) Return(err error) *InstanceCloud_AttachInstanceToSecurityGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InstanceCloud_AttachInstanceToSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, instanceID uuid.UUID, securityGroupID uuid.UUID) error) *InstanceCloud_AttachInstanceToSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInstance provides a mock function for the type InstanceCloud
func (_mock *InstanceCloud) CreateInstance(ctx context.Context, spec domain.ResolvedInstanceSpec) (uuid.UUID, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstance")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ResolvedInstanceSpec) (uuid.UUID, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ResolvedInstanceSpec) uuid.UUID); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ResolvedInstanceSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceCloud_CreateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstance'
type InstanceCloud_CreateInstance_Call struct {
	*mock.Call
}

// CreateInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - spec domain.ResolvedInstanceSpec
func (_e *InstanceCloud_Expecter) CreateInstance(ctx any, spec any) *InstanceCloud_CreateInstance_Call {
	return &InstanceCloud_CreateInstance_Call{Call: _e.mock.On("CreateInstance", ctx, spec)}
}

func (_c *InstanceCloud_CreateInstance_Call) Run(run func(ctx context.Context, spec domain.ResolvedInstanceSpec)) *InstanceCloud_CreateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ResolvedInstanceSpec
		if args[1] != nil {
			arg1 = args[1].(domain.ResolvedInstanceSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InstanceCloud_CreateInstance_Call) Return(uUID uuid.UUID, err error) *InstanceCloud_CreateInstance_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *InstanceCloud_CreateInstance_Call) RunAndReturn(run func(ctx context.Context, spec domain.ResolvedInstanceSpec) (uuid.UUID, error)) *InstanceCloud_CreateInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInstance provides a mock function for the type InstanceCloud
func (_mock *InstanceCloud) DeleteInstance(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InstanceCloud_DeleteInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInstance'
type InstanceCloud_DeleteInstance_Call struct {
	*mock.Call
}

// DeleteInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *InstanceCloud_Expecter) DeleteInstance(ctx any, id any) *InstanceCloud_DeleteInstance_Call {
	return &InstanceCloud_DeleteInstance_Call{Call: _e.mock.On("DeleteInstance", ctx, id)}
}

func (_c *InstanceCloud_DeleteInstance_Call) Run(run func(ctx context.Context, id uuid.UUID)) *InstanceCloud_DeleteInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InstanceCloud_DeleteInstance_Call) Return(err error) *InstanceCloud_DeleteInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InstanceCloud_DeleteInstance_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *InstanceCloud_DeleteInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DetachInstanceFromSecurityGroup provides a mock function for the type InstanceCloud
func (_mock *InstanceCloud) DetachInstanceFromSecurityGroup(ctx context.Context, instanceID uuid.UUID, securityGroupID uuid.UUID) error {
	ret := _mock.Called(ctx, instanceID, securityGroupID)

	if len(ret) == 0 {
		panic("no return value specified for DetachInstanceFromSecurityGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, instanceID, securityGroupID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InstanceCloud_DetachInstanceFromSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachInstanceFromSecurityGroup'
type InstanceCloud_DetachInstanceFromSecurityGroup_Call struct {
	*mock.Call
}

// DetachInstanceFromSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID uuid.UUID
//   - securityGroupID uuid.UUID
func (_e *InstanceCloud_Expecter) DetachInstanceFromSecurityGroup(ctx any, instanceID any, securityGroupID any) *InstanceCloud_DetachInstanceFromSecurityGroup_Call {
	return &InstanceCloud_DetachInstanceFromSecurityGroup_Call{Call: _e.mock.On("DetachInstanceFromSecurityGroup", ctx, instanceID, securityGroupID)}
}

func (_c *InstanceCloud_DetachInstanceFromSecurityGroup_Call) Run(run func(ctx context.Context, instanceID uuid.UUID, securityGroupID uuid.UUID)) *InstanceCloud_DetachInstanceFromSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InstanceCloud_DetachInstanceFromSecurityGroup_Call) Return(err error) *InstanceCloud_DetachInstanceFromSecurityGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InstanceCloud_DetachInstanceFromSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, instanceID uuid.UUID, securityGroupID uuid.UUID) error) *InstanceCloud_DetachInstanceFromSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type InstanceCloud
func (_mock *InstanceCloud) GetInstance(ctx context.Context, id uuid.UUID) (domain.Instance, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 domain.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Instance, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Instance); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceCloud_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type InstanceCloud_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *InstanceCloud_Expecter) GetInstance(ctx any, id any) *InstanceCloud_GetInstance_Call {
	return &InstanceCloud_GetInstance_Call{Call: _e.mock.On("GetInstance", ctx, id)}
}

func (_c *InstanceCloud_GetInstance_Call) Run(run func(ctx context.Context, id uuid.UUID)) *InstanceCloud_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InstanceCloud_GetInstance_Call) Return(instance domain.Instance, err error) *InstanceCloud_GetInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *InstanceCloud_GetInstance_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Instance, error)) *InstanceCloud_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function for the type InstanceCloud
func (_mock *InstanceCloud) GetTemplate(ctx context.Context, id uuid.UUID) (domain.InstanceTemplate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 domain.InstanceTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.InstanceTemplate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.InstanceTemplate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.InstanceTemplate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceCloud_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type InstanceCloud_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *InstanceCloud_Expecter) GetTemplate(ctx any, id any) *InstanceCloud_GetTemplate_Call {
	return &InstanceCloud_GetTemplate_Call{Call: _e.mock.On("GetTemplate", ctx, id)}
}

func (_c *InstanceCloud_GetTemplate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *InstanceCloud_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InstanceCloud_GetTemplate_Call) Return(instanceTemplate domain.InstanceTemplate, err error) *InstanceCloud_GetTemplate_Call {
	_c.Call.Return(instanceTemplate, err)
	return _c
}

func (_c *InstanceCloud_GetTemplate_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.InstanceTemplate, error)) *InstanceCloud_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstanceTypes provides a mock function for the type InstanceCloud
func (_mock *InstanceCloud) ListInstanceTypes(ctx context.Context) ([]domain.InstanceType, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListInstanceTypes")
	}

	var r0 []domain.InstanceType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.InstanceType, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.InstanceType); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InstanceType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceCloud_ListInstanceTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstanceTypes'
type InstanceCloud_ListInstanceTypes_Call struct {
	*mock.Call
}

// ListInstanceTypes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *InstanceCloud_Expecter) ListInstanceTypes(ctx any) *InstanceCloud_ListInstanceTypes_Call {
	return &InstanceCloud_ListInstanceTypes_Call{Call: _e.mock.On("ListInstanceTypes", ctx)}
}

func (_c *InstanceCloud_ListInstanceTypes_Call) Run(run func(ctx context.Context)) *InstanceCloud_ListInstanceTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *InstanceCloud_ListInstanceTypes_Call) Return(instanceTypes []domain.InstanceType, err error) *InstanceCloud_ListInstanceTypes_Call {
	_c.Call.Return(instanceTypes, err)
	return _c
}

func (_c *InstanceCloud_ListInstanceTypes_Call) RunAndReturn(run func(ctx context.Context) ([]domain.InstanceType, error)) *InstanceCloud_ListInstanceTypes_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstances provides a mock function for the type InstanceCloud
func (_mock *InstanceCloud) ListInstances(ctx context.Context, label string) ([]domain.Instance, error) {
	ret := _mock.Called(ctx, label)

	if len(ret) == 0 {
		panic("no return value specified for ListInstances")
	}

	var r0 []domain.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Instance, error)); ok {
		return returnFunc(ctx, label)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Instance); ok {
		r0 = returnFunc(ctx, label)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, label)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceCloud_ListInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstances'
type InstanceCloud_ListInstances_Call struct {
	*mock.Call
}

// ListInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - label string
func (_e *InstanceCloud_Expecter) ListInstances(ctx any, label any) *InstanceCloud_ListInstances_Call {
	return &InstanceCloud_ListInstances_Call{Call: _e.mock.On("ListInstances", ctx, label)}
}

func (_c *InstanceCloud_ListInstances_Call) Run(run func(ctx context.Context, label string)) *InstanceCloud_ListInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InstanceCloud_ListInstances_Call) Return(instances []domain.Instance, err error) *InstanceCloud_ListInstances_Call {
	_c.Call.Return(instances, err)
	return _c
}

func (_c *InstanceCloud_ListInstances_Call) RunAndReturn(run func(ctx context.Context, label string) ([]domain.Instance, error)) *InstanceCloud_ListInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ListTemplates provides a mock function for the type InstanceCloud
func (_mock *InstanceCloud) ListTemplates(ctx context.Context) ([]domain.InstanceTemplate, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTemplates")
	}

	var r0 []domain.InstanceTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.InstanceTemplate, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.InstanceTemplate); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InstanceTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InstanceCloud_ListTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTemplates'
type InstanceCloud_ListTemplates_Call struct {
	*mock.Call
}

// ListTemplates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *InstanceCloud_Expecter) ListTemplates(ctx any) *InstanceCloud_ListTemplates_Call {
	return &InstanceCloud_ListTemplates_Call{Call: _e.mock.On("ListTemplates", ctx)}
}

func (_c *InstanceCloud_ListTemplates_Call) Run(run func(ctx context.Context)) *InstanceCloud_ListTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *InstanceCloud_ListTemplates_Call) Return(instanceTemplates []domain.InstanceTemplate, err error) *InstanceCloud_ListTemplates_Call {
	_c.Call.Return(instanceTemplates, err)
	return _c
}

func (_c *InstanceCloud_ListTemplates_Call) RunAndReturn(run func(ctx context.Context) ([]domain.InstanceTemplate, error)) *InstanceCloud_ListTemplates_Call {
	_c.Call.Return(run)
	return _c
}
