// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/exoscale/cluster-api-provider-exoscale/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSecurityGroupService creates a new instance of SecurityGroupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecurityGroupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecurityGroupService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &SecurityGroupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// SecurityGroupService is an autogenerated mock type for the SecurityGroupService type
type SecurityGroupService struct {
	mock.Mock
}

type SecurityGroupService_Expecter struct {
	mock *mock.Mock
}

func (_m *SecurityGroupService) EXPECT() *SecurityGroupService_Expecter {
	return &SecurityGroupService_Expecter{mock: &_m.Mock}
}

// DeleteSecurityGroup provides a mock function for the type SecurityGroupService
func (_mock *SecurityGroupService) DeleteSecurityGroup(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecurityGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecurityGroupService_DeleteSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecurityGroup'
type SecurityGroupService_DeleteSecurityGroup_Call struct {
	*mock.Call
}

// DeleteSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *SecurityGroupService_Expecter) DeleteSecurityGroup(ctx any, id any) *SecurityGroupService_DeleteSecurityGroup_Call {
	return &SecurityGroupService_DeleteSecurityGroup_Call{Call: _e.mock.On("DeleteSecurityGroup", ctx, id)}
}

func (_c *SecurityGroupService_DeleteSecurityGroup_Call) Run(run func(ctx context.Context, id uuid.UUID)) *SecurityGroupService_DeleteSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecurityGroupService_DeleteSecurityGroup_Call) Return(err error) *SecurityGroupService_DeleteSecurityGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecurityGroupService_DeleteSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *SecurityGroupService_DeleteSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeSecurityGroup provides a mock function for the type SecurityGroupService
func (_mock *SecurityGroupService) PurgeSecurityGroup(ctx context.Context, sgID uuid.UUID) error {
	ret := _mock.Called(ctx, sgID)

	if len(ret) == 0 {
		panic("no return value specified for PurgeSecurityGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sgID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecurityGroupService_PurgeSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeSecurityGroup'
type SecurityGroupService_PurgeSecurityGroup_Call struct {
	*mock.Call
}

// PurgeSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - sgID uuid.UUID
func (_e *SecurityGroupService_Expecter) PurgeSecurityGroup(ctx any, sgID any) *SecurityGroupService_PurgeSecurityGroup_Call {
	return &SecurityGroupService_PurgeSecurityGroup_Call{Call: _e.mock.On("PurgeSecurityGroup", ctx, sgID)}
}

func (_c *SecurityGroupService_PurgeSecurityGroup_Call) Run(run func(ctx context.Context, sgID uuid.UUID)) *SecurityGroupService_PurgeSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecurityGroupService_PurgeSecurityGroup_Call) Return(err error) *SecurityGroupService_PurgeSecurityGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecurityGroupService_PurgeSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, sgID uuid.UUID) error) *SecurityGroupService_PurgeSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertSecurityGroup provides a mock function for the type SecurityGroupService
func (_mock *SecurityGroupService) UpsertSecurityGroup(ctx context.Context, clusterID uuid.UUID, scID *uuid.UUID, name string) (domain.SecurityGroup, error) {
	ret := _mock.Called(ctx, clusterID, scID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSecurityGroup")
	}

	var r0 domain.SecurityGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, string) (domain.SecurityGroup, error)); ok {
		return returnFunc(ctx, clusterID, scID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, string) domain.SecurityGroup); ok {
		r0 = returnFunc(ctx, clusterID, scID, name)
	} else {
		r0 = ret.Get(0).(domain.SecurityGroup)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, clusterID, scID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecurityGroupService_UpsertSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSecurityGroup'
type SecurityGroupService_UpsertSecurityGroup_Call struct {
	*mock.Call
}

// UpsertSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID uuid.UUID
//   - scID *uuid.UUID
//   - name string
func (_e *SecurityGroupService_Expecter) UpsertSecurityGroup(ctx any, clusterID any, scID any, name any) *SecurityGroupService_UpsertSecurityGroup_Call {
	return &SecurityGroupService_UpsertSecurityGroup_Call{Call: _e.mock.On("UpsertSecurityGroup", ctx, clusterID, scID, name)}
}

func (_c *SecurityGroupService_UpsertSecurityGroup_Call) Run(run func(ctx context.Context, clusterID uuid.UUID, scID *uuid.UUID, name string)) *SecurityGroupService_UpsertSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SecurityGroupService_UpsertSecurityGroup_Call) Return(securityGroup domain.SecurityGroup, err error) *SecurityGroupService_UpsertSecurityGroup_Call {
	_c.Call.Return(securityGroup, err)
	return _c
}

func (_c *SecurityGroupService_UpsertSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, clusterID uuid.UUID, scID *uuid.UUID, name string) (domain.SecurityGroup, error)) *SecurityGroupService_UpsertSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertSecurityGroupRules provides a mock function for the type SecurityGroupService
func (_mock *SecurityGroupService) UpsertSecurityGroupRules(ctx context.Context, sgID uuid.UUID, desiredRules []domain.SecurityGroupRule) ([]domain.SecurityGroupRule, error) {
	ret := _mock.Called(ctx, sgID, desiredRules)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSecurityGroupRules")
	}

	var r0 []domain.SecurityGroupRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []domain.SecurityGroupRule) ([]domain.SecurityGroupRule, error)); ok {
		return returnFunc(ctx, sgID, desiredRules)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []domain.SecurityGroupRule) []domain.SecurityGroupRule); ok {
		r0 = returnFunc(ctx, sgID, desiredRules)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SecurityGroupRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []domain.SecurityGroupRule) error); ok {
		r1 = returnFunc(ctx, sgID, desiredRules)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecurityGroupService_UpsertSecurityGroupRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSecurityGroupRules'
type SecurityGroupService_UpsertSecurityGroupRules_Call struct {
	*mock.Call
}

// UpsertSecurityGroupRules is a helper method to define mock.On call
//   - ctx context.Context
//   - sgID uuid.UUID
//   - desiredRules []domain.SecurityGroupRule
func (_e *SecurityGroupService_Expecter) UpsertSecurityGroupRules(ctx any, sgID any, desiredRules any) *SecurityGroupService_UpsertSecurityGroupRules_Call {
	return &SecurityGroupService_UpsertSecurityGroupRules_Call{Call: _e.mock.On("UpsertSecurityGroupRules", ctx, sgID, desiredRules)}
}

func (_c *SecurityGroupService_UpsertSecurityGroupRules_Call) Run(run func(ctx context.Context, sgID uuid.UUID, desiredRules []domain.SecurityGroupRule)) *SecurityGroupService_UpsertSecurityGroupRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []domain.SecurityGroupRule
		if args[2] != nil {
			arg2 = args[2].([]domain.SecurityGroupRule)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SecurityGroupService_UpsertSecurityGroupRules_Call) Return(securityGroupRules []domain.SecurityGroupRule, err error) *SecurityGroupService_UpsertSecurityGroupRules_Call {
	_c.Call.Return(securityGroupRules, err)
	return _c
}

func (_c *SecurityGroupService_UpsertSecurityGroupRules_Call) RunAndReturn(run func(ctx context.Context, sgID uuid.UUID, desiredRules []domain.SecurityGroupRule) ([]domain.SecurityGroupRule, error)) *SecurityGroupService_UpsertSecurityGroupRules_Call {
	_c.Call.Return(run)
	return _c
}
