apiVersion: cluster.k8s.io/v1alpha1
kind: MachineList
items:
# Master machine
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: my-exoscale-master-
    labels:
      cluster.k8s.io/cluster-name: my-exoscale-cluster-testt
      set: master
  spec:
    providerID: Exoscale
    providerSpec:
      value:
        apiVersion: exoscale.cluster.k8s.io/v1alpha1
        kind: ExoscaleMachineProviderSpec
        zone: de-fra-1
        # if template not provisioned we recommend only ubuntu template
        # provisioned template example (docker, kubelet, kubeadm)
        template: "k8s-node"
        type: medium
        disk: 50
    versions:
      kubelet: 1.14.0
      controlPlane: 1.14.0
# Worker machine
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: my-exoscale-node-
    labels:
      cluster.k8s.io/cluster-name: my-exoscale-cluster-testt
      set: node
  spec:
    providerID: Exoscale
    providerSpec:
      value:
        apiVersion: exoscale.cluster.k8s.io/v1alpha1
        kind: ExoscaleMachineProviderSpec
        zone: de-fra-1
         # if template not provisioned we recommend only ubuntu
         # provisioned template example (docker, kubelet, kubeadm)
        template: "k8s-node"
        type: medium
        disk: 50
    versions:
      kubelet: 1.14.0
