apiVersion: cluster.k8s.io/v1alpha1
kind: MachineList
items:
# Master machine
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: my-exoscale-master-
    labels:
      cluster.k8s.io/cluster-name: my-exoscale-cluster-pv
      set: master
  spec:
    providerID: Exoscale
    providerSpec:
      value:
        apiVersion: exoscale.cluster.k8s.io/v1alpha1
        kind: ExoscaleMachineProviderSpec
        zone: de-fra-1
        # if template not provisioned we recommend only ubuntu template
        # provisioned template example (docker, kubelet, kubeadm)
        template: "k8s-node"
        type: medium
        disk: 200
        # Example of cloudinit
        cloudinit: |
          #cloud-config
          growpart:
          mode: off
          devices: ['/']
          runcmd:
           - sgdisk -e /dev/vda
           - parted -a optimal -s /dev/vda -- mkpart LOCAL-PV ext4 30GB -1
           - growpart /dev/vda 1
           - resize2fs /dev/vda1
           - modprobe dm_thin_pool
           - mkdir /mtn/disks/vol1
           - mount -t tmpfs /dev/vda2 /mnt/disks/vol1
           - echo "/dev/vda2 /mnt/disks/vol1 ext4 defaults    0 0" >> /etc/fstab
 
    versions:
      kubelet: 1.14.0
      controlPlane: 1.14.0
# Worker machine
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: my-exoscale-node-
    labels:
      cluster.k8s.io/cluster-name: my-exoscale-cluster-pv
      set: node
  spec:
    providerID: Exoscale
    providerSpec:
      value:
        apiVersion: exoscale.cluster.k8s.io/v1alpha1
        kind: ExoscaleMachineProviderSpec
        zone: de-fra-1
         # if template not provisioned we recommend only ubuntu
         # provisioned template example (docker, kubelet, kubeadm)
        template: "k8s-node"
        type: medium
        disk: 200
        # Example of cloudinit
        cloudinit: |
          #cloud-config
          growpart:
          mode: off
          devices: ['/']
          runcmd:
           - sgdisk -e /dev/vda
           - parted -a optimal -s /dev/vda -- mkpart LOCAL-PV ext4 30GB -1
           - growpart /dev/vda 1
           - resize2fs /dev/vda1
           - modprobe dm_thin_pool
           - mkdir /mtn/disks/vol1
           - mount -t tmpfs /dev/vda2 /mnt/disks/vol1
           - echo "/dev/vda2 /mnt/disks/vol1 ext4 defaults    0 0" >> /etc/fstab
    versions:
      kubelet: 1.14.0
