---
- op: add
  path: "/rules/-"
  value:
    apiGroups:
    - cluster.k8s.io
    resources:
    - clusters
    - clusters/status
    - machines
    - machines/status
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
