apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exoscale-provider-manager-role
rules:
- apiGroups:
  - exoscaleproviderconfig.k8s.io
  resources:
  - exoscalemachineproviderconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cluster.k8s.io
  resources:
  - clusters
  - machines
  - machinedeployments
  - machinesets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch