apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../cluster
patches:
- target:
    kind: ExoscaleMachineTemplate
  patch: |-
    - op: replace
      path: /spec/template/spec/template
      value: REPLACE_WITH_TEMPLATE_UUID
- target:
    kind: KubeadmControlPlane
    name: my-control-plane
  patch: |-
    - op: replace
      path: /spec/version
      value: v1.36.4
    - op: replace
      path: /spec/kubeadmConfigSpec/preKubeadmCommands
      value:
      - |
         set -eux
         printf 'KUBELET_EXTRA_ARGS=--provider-id=exoscale://%s --node-labels=topology.kubernetes.io/zone=ch-gva-2,topology.kubernetes.io/region=ch-gva-2\n' \
           "$(cat /var/lib/cloud/data/instance-id)" >/etc/default/kubelet
- target:
    kind: KubeadmConfigTemplate
    name: my-workers
  patch: |-
    - op: replace
      path: /spec/template/spec/preKubeadmCommands
      value:
      - |
        set -eux
        printf 'KUBELET_EXTRA_ARGS=--provider-id=exoscale://%s --node-labels=topology.kubernetes.io/zone=ch-gva-2,topology.kubernetes.io/region=ch-gva-2\n' \
          "$(cat /var/lib/cloud/data/instance-id)" >/etc/default/kubelet
- target:
    kind: MachineDeployment
    name: my-workers
  patch: |-
    - op: replace
      path: /spec/template/spec/version
      value: v1.36.4
