apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- infrastructure_v1alpha1_exoscaleclustertemplate.yaml
- infrastructure_v1alpha1_exoscalemachinetemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
