// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderConfig) DeepCopyInto(out *ExoscaleClusterProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderConfig.
func (in *ExoscaleClusterProviderConfig) DeepCopy() *ExoscaleClusterProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleClusterProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderConfigList) DeepCopyInto(out *ExoscaleClusterProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExoscaleClusterProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderConfigList.
func (in *ExoscaleClusterProviderConfigList) DeepCopy() *ExoscaleClusterProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleClusterProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderConfigSpec) DeepCopyInto(out *ExoscaleClusterProviderConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderConfigSpec.
func (in *ExoscaleClusterProviderConfigSpec) DeepCopy() *ExoscaleClusterProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderConfigStatus) DeepCopyInto(out *ExoscaleClusterProviderConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderConfigStatus.
func (in *ExoscaleClusterProviderConfigStatus) DeepCopy() *ExoscaleClusterProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderConfig) DeepCopyInto(out *ExoscaleMachineProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderConfig.
func (in *ExoscaleMachineProviderConfig) DeepCopy() *ExoscaleMachineProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleMachineProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderConfigList) DeepCopyInto(out *ExoscaleMachineProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExoscaleMachineProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderConfigList.
func (in *ExoscaleMachineProviderConfigList) DeepCopy() *ExoscaleMachineProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleMachineProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderConfigSpec) DeepCopyInto(out *ExoscaleMachineProviderConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderConfigSpec.
func (in *ExoscaleMachineProviderConfigSpec) DeepCopy() *ExoscaleMachineProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderConfigStatus) DeepCopyInto(out *ExoscaleMachineProviderConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderConfigStatus.
func (in *ExoscaleMachineProviderConfigStatus) DeepCopy() *ExoscaleMachineProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}
