// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderSpec) DeepCopyInto(out *ExoscaleClusterProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderSpec.
func (in *ExoscaleClusterProviderSpec) DeepCopy() *ExoscaleClusterProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleClusterProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderSpecList) DeepCopyInto(out *ExoscaleClusterProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExoscaleClusterProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderSpecList.
func (in *ExoscaleClusterProviderSpecList) DeepCopy() *ExoscaleClusterProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleClusterProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderSpecSpec) DeepCopyInto(out *ExoscaleClusterProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderSpecSpec.
func (in *ExoscaleClusterProviderSpecSpec) DeepCopy() *ExoscaleClusterProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderSpecStatus) DeepCopyInto(out *ExoscaleClusterProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderSpecStatus.
func (in *ExoscaleClusterProviderSpecStatus) DeepCopy() *ExoscaleClusterProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderStatus) DeepCopyInto(out *ExoscaleClusterProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderStatus.
func (in *ExoscaleClusterProviderStatus) DeepCopy() *ExoscaleClusterProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleClusterProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderStatusList) DeepCopyInto(out *ExoscaleClusterProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExoscaleClusterProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderStatusList.
func (in *ExoscaleClusterProviderStatusList) DeepCopy() *ExoscaleClusterProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleClusterProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderStatusSpec) DeepCopyInto(out *ExoscaleClusterProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderStatusSpec.
func (in *ExoscaleClusterProviderStatusSpec) DeepCopy() *ExoscaleClusterProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleClusterProviderStatusStatus) DeepCopyInto(out *ExoscaleClusterProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleClusterProviderStatusStatus.
func (in *ExoscaleClusterProviderStatusStatus) DeepCopy() *ExoscaleClusterProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(ExoscaleClusterProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderSpec) DeepCopyInto(out *ExoscaleMachineProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderSpec.
func (in *ExoscaleMachineProviderSpec) DeepCopy() *ExoscaleMachineProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleMachineProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderSpecList) DeepCopyInto(out *ExoscaleMachineProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExoscaleMachineProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderSpecList.
func (in *ExoscaleMachineProviderSpecList) DeepCopy() *ExoscaleMachineProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleMachineProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderSpecSpec) DeepCopyInto(out *ExoscaleMachineProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderSpecSpec.
func (in *ExoscaleMachineProviderSpecSpec) DeepCopy() *ExoscaleMachineProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderSpecStatus) DeepCopyInto(out *ExoscaleMachineProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderSpecStatus.
func (in *ExoscaleMachineProviderSpecStatus) DeepCopy() *ExoscaleMachineProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderStatus) DeepCopyInto(out *ExoscaleMachineProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderStatus.
func (in *ExoscaleMachineProviderStatus) DeepCopy() *ExoscaleMachineProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleMachineProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderStatusList) DeepCopyInto(out *ExoscaleMachineProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExoscaleMachineProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderStatusList.
func (in *ExoscaleMachineProviderStatusList) DeepCopy() *ExoscaleMachineProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleMachineProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderStatusSpec) DeepCopyInto(out *ExoscaleMachineProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderStatusSpec.
func (in *ExoscaleMachineProviderStatusSpec) DeepCopy() *ExoscaleMachineProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleMachineProviderStatusStatus) DeepCopyInto(out *ExoscaleMachineProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleMachineProviderStatusStatus.
func (in *ExoscaleMachineProviderStatusStatus) DeepCopy() *ExoscaleMachineProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(ExoscaleMachineProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}
