apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default
  - ../network-policy

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cluster-api-provider-exoscale-controller-manager
      spec:
        template:
          spec:
            containers:
              - name: manager
                imagePullPolicy: Never
    target:
      kind: Deployment
      name: cluster-api-provider-exoscale-controller-manager
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --zap-log-level=4
    target:
      kind: Deployment
      name: cluster-api-provider-exoscale-controller-manager
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: cluster-api-provider-exoscale-system
    target:
      kind: NetworkPolicy
