name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: e2e-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  chainsaw:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /usr/local/.ghcup
          sudo docker image prune --all --force

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Install kind
        run: go install sigs.k8s.io/kind@v0.32.0

      - name: Run Chainsaw
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          CHAINSAW_MACHINE_TEMPLATE: Linux Ubuntu 24.04 LTS 64-bit
          EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
        run: |
          make chainsaw-test-e2e CHAINSAW_VALUES_SUFFIX=$COMMIT_SHA
