name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test

      - name: Validate clusterctl assets
        env:
          IMAGE: exoscale/cluster-api-provider-exoscale-controller:test
        run: |
          make build-installer yq IMG="$IMAGE"
          test "$(bin/yq '.apiVersion' metadata.yaml)" = clusterctl.cluster.x-k8s.io/v1alpha3
          test "$(bin/yq '.kind' metadata.yaml)" = Metadata
          test "$(bin/yq '.releaseSeries[0].contract' metadata.yaml)" = v1beta2
          test "$(bin/yq 'select(.kind == "Deployment") | .spec.template.spec.containers[] | select(.name == "manager") | .image' dist/install.yaml)" = "$IMAGE"
